'''
Autogenerated Method-Stub for:
module vrAmbientOcclusion
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def computeAmbientOcclusion(materialColorG, gatherQuality, subdivisionQuality, maxDistance, quality, minDistance, minEdgeLength, colorBleeding, overrideMaterialColor, numIndirections, materialColorB, intensityThreshold, subdivide, indirectIllumination, materialColorR):
    '''
    Calculates ambient occlusion and indirect illumination including color bleeding.
    '''
    pass



def computeMissingAmbientOcclusion(materialColorG, gatherQuality, subdivisionQuality, maxDistance, quality, minDistance, minEdgeLength, colorBleeding, overrideMaterialColor, numIndirections, materialColorB, intensityThreshold, subdivide, indirectIllumination, materialColorR):
    '''
    Calculates ambient occlusion and indirect illumination including color bleeding for the selected nodes that do not have a calculation yet.
    '''
    pass



def getAmbientOcclusionMode():
    '''
    Returns the current ambient occlusion mode.
    '''
    pass



def setAmbientOcclusionMode(mode):
    '''
    Sets the ambient occlusion mode.
    '''
    pass


