
# Autogenerated method stubs for 'vrAnnotation.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def createAnnotation(name):
    '''
    Creates a new annotation.

@param name: The name of the new annotation. The name is made unique.

@type name: string

@return: The created annotation.

@rtype: vrAnnotationPtr
    '''
    pass



def deleteAnnotations(annotations):
    '''
    Deletes the annotations.

@param annotations: list of the annotations to delete.

@type annotations: list of vrAnnotationPtr
    '''
    pass



def duplicateAnnotation(annotation):
    '''
    Duplicates the annotation.

@param annotation: source annotation

@type annotation: vrAnnotationPtr

@return: The copy.

@rtype: vrAnnotationPtr
    '''
    pass



def findAnnotation(name):
    '''
    Find an annotation by name. If multiple annotations have the same name, the first one is returned.

@param name: The name of the annotation.

@type name: string

@return: Found annotation or None if not found.

@rtype: vrAnnotationPtr or None
    '''
    pass



def getAnnotations():
    '''
    Get a list of all annotations.

@return: List of annotations.

@rtype: list of vrAnnotationPtr
    '''
    pass



def getShowAnnotations():
    '''
    Returns whether annotation visualizations are shown.

@return: True if annotations shown, false if hidden.

@rtype: bool
    '''
    pass



def loadAnnotationsXML(path):
    '''
    Loads annotations from XML file and adds them to the scene.

@param path: XML file path

@type path: string

@return: list of loaded annotations

@rtype: list of vrAnnotationPtr
    '''
    pass



def pickAnnotation(annotation):
    '''
    Activates the picking tool in the render window to reposition the given annotation.

@param annotation: annotation

@type annotation: vrAnnotationPtr
    '''
    pass



def saveAnnotationsXML(path, annotations):
    '''
    Saves annotations to an XML file. Omit second parameter to save all annotations.

@param path: XML file path

@type path: string

@param annotations: list of annotations to save (Optional)

@type annotations: list of vrAnnotationPtr
    '''
    pass



def setShowAnnotations(state):
    '''
    Shows/hides all annotations.

@param state: Toggle show/hide.

@type state: bool
    '''
    pass


