'''
Autogenerated Method-Stub for:
module vrAnimation
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def continueAnimation(name):
    '''
    Continues an animation.
    '''
    pass



def getAnimations():
    '''
    Returns all animations.
    '''
    pass



def pauseAnimation(name):
    '''
    Pauses an animation.
    '''
    pass



def resetAnimation(name):
    '''
    Resets an animation.
    '''
    pass



def startAnimation(name):
    '''
    Starts an animation.
    '''
    pass



def stopAnimation(name):
    '''
    Stops an animation.
    '''
    pass



def toggleAnimation(name):
    '''
    Toggles an animation.
    '''
    pass


