'''
vrAnimation
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def continueAnimation(name):
    '''
    Continues an animation.
    '''
    pass


def getAnimations():
    '''
    Returns all animations.
    '''
    pass


def pauseAnimation(name):
    '''
    Pauses an animation.
    '''
    pass


def resetAnimation(name):
    '''
    Resets an animation.
    '''
    pass


def startAnimation(name):
    '''
    Starts an animation.
    '''
    pass


def stopAnimation(name):
    '''
    Stops an animation.
    '''
    pass


def toggleAnimation(name):
    '''
    Toggles an animation.
    '''
    pass

