'''
Autogenerated Method-Stub for:
module vrCameraService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createCamera(name, mode, constraint, sceneGraphParentNode, cameraGraphParentNode):
    '''
    Creates a new camera.
    '''
    pass



def createCameraGroup(name, cameraGraphParentNode):
    '''
    Creates a new camera group.
    '''
    pass



def createCameraTrack(name, cameraNode):
    '''
    Creates a new camera track.
    '''
    pass



def createViewpoint(name, cameraTrack):
    '''
    Creates a new viewpoint.
    '''
    pass



def duplicateNode(node):
    '''
    Creates a copy of a camera tree node (including its children).
    '''
    pass



def getActiveCamera(useCameraGraph):
    '''
    Returns the active camera of the currently active viewport.
    '''
    pass



def getAllCameraTracks():
    '''
    Returns the list of all camera tracks.
    '''
    pass



def getAllViewpoints():
    '''
    Returns the list of all viewpoints.
    '''
    pass



def getCamera(name, useCameraGraph):
    '''
    Returns the first camera with the given name.
    '''
    pass



def getCameraNames():
    '''
    Returns a list with the names of all cameras.
    '''
    pass



def getCameraRoot():
    '''
    Returns the root node of cameras, that contains all cameras, camera tracks and viewpoints.
    '''
    pass



def getCameras(useCameraScenegraph):
    '''
    Returns the list of all cameras (not including viewpoints or camera tracks).
    '''
    pass



def getViewpoint(name):
    '''
    Returns the first viewpoint with the given name.
    '''
    pass



def getViewpointCreationMode():
    '''
    Returns if tracking transformation should be included in viewpoint transformation.
    '''
    pass



def load(filename):
    '''
    Load camera related nodes.
    '''
    pass



def saveCameras(nodes, filename):
    '''
    Save cameras and viewpoints to an .xml file (no hierarchy, groups or tracks supported).
    '''
    pass



def saveNodes(nodes, filename):
    '''
    Save nodes including children (tracks, groups, viewpoints) to .osb file.
    '''
    pass



def saveViewpoints(filename):
    '''
    Save all viewpoints to ‘.xml’ file.
    '''
    pass



def setViewpointCreationMode(mode):
    '''
    Defines if tracking transformation should be included in viewpoint transformation.
    '''
    pass


