
# Autogenerated method stubs for 'vrCluster.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getClusterRunning():
    '''
    Return true if the Cluster is running

@type isRunning: bool
    '''
    pass



def getHPCRunning():
    '''
    DEPRECATED. Use getClusterRunning instead.

Return true if the hpc cluster is running

@type filename: bool
    '''
    pass



def hasClusterLicense():
    '''
    Return true if the Cluster has valid licenses

@type hasLicense: bool
    '''
    pass



def loadCluster(filename):
    '''
    Loads the cluster configuration.

@param filename: The name of the XML-file with the cluster configuration.

@type filename: string
    '''
    pass



def loadHPC(filename):
    '''
    DEPRECATED. Use loadCluster instead.

Loads the hpc cluster configuration.

@param filename: The name of the XML-file with the cluster configuration.

@type filename: string
    '''
    pass



def loginToClusterManager(server, user, password):
    '''
    Login to cluster manager.

@param server: Hostname of the cluster manager

@type server: string

@param user: User name used to login into cluster manager

@type user: string

@param password: Password used to login into cluster manager

@type password: string
    '''
    pass



def logoffFromClusterManager():
    '''
    Logoff from cluster manager.
    '''
    pass



def renderOnClusterQueue(queue):
    '''
    Start rendering on cluster queue

@param queue: Name of the cluster queue

@type queue: string
    '''
    pass



def renderQueueOnClusterQueue(queue):
    '''
    Start rendering the queue on cluster queue

@param queue: Name of the cluster queue

@type queue: string
    '''
    pass



def renderSequencesOnClusterQueue(queue):
    '''
    Start rendering sequences on cluster queue

@param queue: Name of the cluster queue

@type queue: string
    '''
    pass



def setClusterAdvanced():
    '''
    DEPRECATED. This function is not used anymore.
    '''
    pass



def setClusterConnectionDelay():
    '''
    DEPRECATED. This function is not used anymore.
    '''
    pass



def setClusterEyeSeparation(es):
    '''
    Sets the cluster eye separation.

@param es: The eye separation.

@type es: float
    '''
    pass



def setClusterNetworkSpeed():
    '''
    Used to change cluster network speed hint
    '''
    pass



def setClusterNetworkType():
    '''
    Used to change cluster network interface
    '''
    pass



def setClusterNodes(hosts):
    '''
    Sets the list of compute nodes.

@param hosts: List of host names.

@type hosts: string
    '''
    pass



def setClusterProjectionPlane():
    '''
    DEPRECATED. This function is not used anymore.
    '''
    pass



def setClusterZeroParallax(zp):
    '''
    Sets the cluster zero parallax.

@param zp: The zero parallax.

@type zp: float
    '''
    pass



def setHPCAdvanced():
    '''
    DEPRECATED. This function is not used anymore.
    '''
    pass



def setHPCNetworkSpeed():
    '''
    DEPRECATED. Use setClusterNetworkSpeed instead.

Used to change hpc network speed hint
    '''
    pass



def setHPCNetworkType():
    '''
    DEPRECATED. Use setClusterNetworkType instead.

Used to change hpc network interface
    '''
    pass



def setHPCNodes(hosts):
    '''
    DEPRECATED. Use setClusterNodes instead.

Sets the list of compute nodes.

@param hosts: List of host names.

@type hosts: string
    '''
    pass



def startBookedRaytracingCluster(bookingId, server, user, password):
    '''
    Start the raytracing cluster.

@param bookingId: Id of the booked session

@type bookingId: string

@param server: Hostname of the cluster manager

@type server: string

@param user: User name used to login into cluster manager

@type user: string

@param password: Password used to login into cluster manager

@type password: string
    '''
    pass



def startCluster():
    '''
    Activates the cluster mode.
    '''
    pass



def startHPC():
    '''
    DEPRECATED. Use startCluster instead.

Activates the hpc cluster mode.
    '''
    pass



def startHPCRaytracing(hosts):
    '''
    DEPRECATED. Use startRaytracingCluster instead.

Starts a cluster with the given compute nodes.

@param hosts: List of host names.

@type hosts: string
    '''
    pass



def startRaytracingCluster(hostnames):
    '''
    Start the raytracing cluster.

@param hostnames: Space separated list of names or ips of the cluster client machines.

@type hostnames: string
    '''
    pass



def stopCluster():
    '''
    Deactivates the cluster mode.
    '''
    pass



def stopHPC():
    '''
    DEPRECATED. Use stopCluster instead.

Deactivates the hpc cluster mode.
    '''
    pass


