'''
vrConstraints
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def createAimConstraint(targetName, upSourceNames, sourceNames):
    '''
    Creates a constraint between nodes: "sources" and "target".
    '''
    pass


def createRotationConstraint(maintainOffset, targetName, sourceNames):
    '''
    Creates a constraint between nodes: "sources" and "target".
    '''
    pass


def createTranslationConstraint(maintainOffset, targetName, sourceNames):
    '''
    Creates a constraint between nodes: "sources" and "target".
    '''
    pass

