'''
vrColorDialog
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def getColorFromDialog(blue, red, green):
    '''
    Opens a color dialog and lets the user choose a color.
    '''
    pass

