'''
vrConnector
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def setConnectorMousePos(y, x):
    '''
    Set mouse position.
    '''
    pass


def setConnectorShowMouseOnClients(state):
    '''
    Enables/disables displaying the mouse on the clients.
    '''
    pass


def setVredFrameSync(state):
    '''
    Enables/disables frame sync.
    '''
    pass


def startVredClient(serverIP, port):
    '''
    Starts a Client.
    '''
    pass


def startVredServer(port):
    '''
    With the vrConnector you can connect two VRED instances synchronizing the navigation as well as python commands.
    '''
    pass


def stopVredClient():
    '''
    Stop Client.
    '''
    pass


def stopVredServer():
    '''
    Stop the server.
    '''
    pass

