'''
Autogenerated Method-Stub for:
module vrConnector
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def setConnectorMousePos(x, y):
    '''
    Set mouse position.
    '''
    pass



def setConnectorShowMouseOnClients(state):
    '''
    Enables/disables displaying the mouse on the clients.
    '''
    pass



def setVredFrameSync(state):
    '''
    Enables/disables frame sync.
    '''
    pass



def startVredClient(serverIP, port):
    '''
    Starts a Client.
    '''
    pass



def startVredServer(port):
    '''
    With the vrConnector you can connect two VRED instances synchronizing the navigation as well as python commands.
    '''
    pass



def stopVredClient():
    '''
    Stop Client.
    '''
    pass



def stopVredServer():
    '''
    Stop the server.
    '''
    pass


