
# Autogenerated method stubs for 'vrColorDialog.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getColorFromDialog(red, green, blue):
    '''
    Opens a color dialog and lets the user choose a color. Actually there are two versions, the first one with integer and the second one with float parameters and return values.

@param red: The red component of the preset color as integer (value from 0 to 255) or float (value from 0.0 to 1.0).

@type red: integer or float

@param green: The green component of the preset color as integer (value from 0 to 255) or float (value from 0.0 to 1.0).

@type green: integer or float

@param blue: The blue component of the preset color as integer (value from 0 to 255) or float (value from 0.0 to 1.0).

@type blue: integer or float

@return: The user-selected colors (element 0 is the red, element 1 is the green and element 2 is the blue component).

@rtype: list of integers or list of floats
    '''
    pass


