
# Autogenerated method stubs for 'vrConstraints.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def createAimConstraint(sourceNames, upSourceNames, targetName):
    '''
    Creates a constraint between nodes: "sources" and "target".

@param sourceNames: The names of the source nodes.

@type sourceNames: list of string

@param upSourceNames: The names of the up source nodes.

@type upSourceNames: list of string

@param targetName: The name of the target node.

@type targetName: string
    '''
    pass



def createRotationConstraint(sourceNames, targetName, maintainOffset):
    '''
    Creates a constraint between nodes: "sources" and "target".

@param sourceNames: The names of the source nodes.

@type sourceNames: list of string

@param targetName: The name of the target node.

@type targetName: string

@param maintainOffset: Maintain current offset.

@type maintainOffset: bool
    '''
    pass



def createTranslationConstraint(sourceNames, targetName, maintainOffset):
    '''
    Creates a constraint between nodes: "sources" and "target".

@param sourceNames: The names of the source nodes.

@type sourceNames: list of string

@param targetName: The name of the target node.

@type targetName: string

@param maintainOffset: Maintain current offset.

@type maintainOffset: bool
    '''
    pass


