'''
Autogenerated Method-Stub for:
module vrCubeImages
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createCubeImages(resolution, filename, type, supersampling, node_name):
    '''
    Exports an environment image.
    '''
    pass


