'''
vrCubeImages
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def createCubeImages(filename, node_name, supersampling, resolution, type):
    '''
    Exports an environment image.
    '''
    pass

