'''
Autogenerated Method-Stub for:
module vrdAreaLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAttenuation():
    '''
    Returns the attenuation mode.
    '''
    pass



def getIlluminateScene():
    '''
    Returns the state of the illuminate scene flag..
    '''
    pass



def getInteractiveQuality():
    '''
    Returns the raytracing quality level for the interactive mode.
    '''
    pass



def getLightProfile():
    '''
    Returns the light profile.
    '''
    pass



def getLocalLight():
    '''
    Returns the state of local lighting.
    '''
    pass



def getPrimaryVisibility():
    '''
    Returns the state of the primary visibility.
    '''
    pass



def getShadowMap():
    '''
    Returns the shadow map of the light.
    '''
    pass



def getStillFrameQuality():
    '''
    Returns the ratracing still frame quality level.
    '''
    pass



def getTexture():
    '''
    Returns the currently used light texture.
    '''
    pass



def getVisibleInReflections():
    '''
    Returns if the light is visible in reflections (Raytracing only).
    '''
    pass



def setAttenuation(attenuation):
    '''
    Sets the attenuation mode. Attenuation is the falloff of the light intensity.
    '''
    pass



def setIlluminateScene(illuminateScene):
    '''
    Toggles the illumination of objects on or off.
    '''
    pass



def setInteractiveQuality(quality):
    '''
    Sets the raytracing quality level for the interactive mode.
    '''
    pass



def setLocalLight(isLocalLight):
    '''
    Enables / disables local lighting.
    '''
    pass



def setPrimaryVisibility(visible):
    '''
    Sets the primary visibility of the light.
    '''
    pass



def setStillFrameQuality(quality):
    '''
    Sets the raytracing quality level for still frame rendering.
    '''
    pass



def setVisibleInReflections(visible):
    '''
    Sets the visibility in reflections.
    '''
    pass


