'''
Autogenerated Method-Stub for:
module vrdAreaLightCone
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getConeAngle():
    '''
    Returns the light cone angle.
    '''
    pass



def getPenumbraAngle():
    '''
    Documentation missing
    '''
    pass



def getUseConeAngle():
    '''
    Returns if custom light cone and penumbra angles are enabled.
    '''
    pass



def setConeAngle(angle):
    '''
    Sets the light cone angle.
    '''
    pass



def setPenumbraAngle(angle):
    '''
    Sets the penumbra angle.
    '''
    pass



def setUseConeAngle(use):
    '''
    Enable usage of custom light cone and penumbra angles.
    '''
    pass


