'''
Autogenerated Method-Stub for:
module vrdAimConstraintNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def clearUpVectorTargetNodes():
    '''
    Clears the set up vector target nodes of the constraint.
    '''
    pass



def getUpVectorTargetNodes():
    '''
    Returns the list of nodes set as up vector targets for the constraint.
    '''
    pass



def getUpVectorTargetNodeWeight(node):
    '''
    Gets the weight for a up vector target node of the constraint. The node must be referenced in the up vector target nodes list of the constraint.
    '''
    pass



def setUpVectorTargetNodes(nodes):
    '''
    Sets a list of nodes as up vector targets for the constraint.
    '''
    pass



def setUpVectorTargetNodeWeight(node, weight):
    '''
    Sets the weight for an up vector target node of the constraint. The node must be referenced in the up vector target nodes list of the constraint.
    '''
    pass


