'''
vrdAreaLightCone
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class provides control of the light cone of an area light.
'''

from typing import List


def getConeAngle() -> float:
    '''
    Returns the light cone angle.
    '''
    return None


def getPenumbraAngle():
    '''
    Documentation missing
    '''
    pass


def getUseConeAngle() -> bool:
    '''
    Returns if custom light cone and penumbra angles are enabled.
    '''
    return None


def setConeAngle(angle: float):
    '''
    Sets the light cone angle.
    '''
    pass


def setPenumbraAngle(angle: float):
    '''
    Sets the penumbra angle.
    '''
    pass


def setUseConeAngle(use: bool):
    '''
    Enable usage of custom light cone and penumbra angles.
    '''
    pass

