'''
Autogenerated Method-Stub for:
module vrdAtfSettings
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getChordDeviation():
    '''
    Get maximum deviation of tessellated mesh to the NURBS surface in mm.
    '''
    pass



def getCreateLayerGroups():
    '''
    Query if creating group nodes from layer information is enabled..
    '''
    pass



def getFixSurfaceOrientation():
    '''
    Query if orienting surface normals is enabled.
    '''
    pass



def getFlushTransformations():
    '''
    Query if transformations should be flushed into the vertex coordinates.
    '''
    pass



def getImportAsSmartReference():
    '''
    Query if smart references should be created for imported vpb files.
    '''
    pass



def getImportAssociativeMeshes():
    '''
    Query if import of associative meshes is enabled.
    '''
    pass



def getImportCameras():
    '''
    Query if import of cameras is enabled.
    '''
    pass



def getImportCoordSystems():
    '''
    Query if import of coordinate system nodes is enabled.
    '''
    pass



def getImportCurves():
    '''
    Query if import of curves and poly lines is enabled.
    '''
    pass



def getImportEmptyLayers():
    '''
    Query if import of empty layers is enabled.
    '''
    pass



def getImportInvisibleCurves():
    '''
    Query if import of curves and poly lines, that are invisible in CAD data, is enabled.
    '''
    pass



def getImportInvisibleInstances():
    '''
    Query if import of invisible instance nodes is enabled.
    '''
    pass



def getImportInvisibleMeshes():
    '''
    Query if import of polygon meshes, that are invisible in the CAD file, is enabled.
    '''
    pass



def getImportInvisibleSurfaces():
    '''
    Query if import of surfaces, that are invisible in the CAD file, is enabled.
    '''
    pass



def getImportLights():
    '''
    Query if import of light sources is enabled.
    '''
    pass



def getImportMeshes():
    '''
    Query if import of polygon meshes is enabled.
    '''
    pass



def getImportMeshLODs():
    '''
    Query which mesh LODs should be imported.
    '''
    pass



def getImportReferencedFiles():
    '''
    Query if import of part files referenced by an assembly is enabled.
    '''
    pass



def getImportSurfaces():
    '''
    Query if import of surfaces is enabled.
    '''
    pass



def getImportTemplateGeometries():
    '''
    Query if import of template geometries is enabled.
    '''
    pass



def getImportVariants():
    '''
    Query if import of variants is enabled.
    '''
    pass



def getJtToolkit():
    '''
    Query which Jt toolkit is used for import.
    '''
    pass



def getKeepNurbs():
    '''
    Query if NURBS data should be kept alongside with tessellation result.
    '''
    pass



def getMaxChordLength():
    '''
    Get maximum length of a triangle edge in mm.
    '''
    pass



def getMergeGeometries():
    '''
    Query if tessellated meshes of adjacent NURBS surfaces with same material should be merged.
    '''
    pass



def getMergeSubReferenceMaterials():
    '''
    Query if duplicate materials, referenced in different files, should be merged into one single material. Materials with same name and identical properties are regarded as duplicates.
    '''
    pass



def getNormalTolerance():
    '''
    Get the normal tolerance of adjacent triangles in degrees.
    '''
    pass



def getReduceKeyframes():
    '''
    Query if reducing the number of keyframes is enabled.
    '''
    pass



def getRemoveEmptyGroups():
    '''
    Query if groups without children should be removed.
    '''
    pass



def getSmartReferenceBehavior():
    '''
    Query how references to VRED native files are treated in import.
    '''
    pass



def getSourceReferenceBehavior():
    '''
    Query how references to files of import file types are treated in import.
    '''
    pass



def getStitchingTolerance():
    '''
    Get the stitching tolerance of adjacent edges in mm.
    '''
    pass



def getUnshareNodes():
    '''
    Query if shared node instances should be converted to independent nodes.
    '''
    pass



def getUseLegacyLoader():
    '''
    Query if using legacy importer is enabled.
    '''
    pass



def getUseStitching():
    '''
    Query if stitching is enabled.
    '''
    pass



def setChordDeviation(chordDeviation):
    '''
    Set maximum allowed distance from the NURBS surface to the tessellated surface in mm. Lower values result in more accurate polygon models but also increase the number of triangles.
    '''
    pass



def setCreateLayerGroups(create):
    '''
    Enable / Disable creation of group nodes for objects organized in layers. In case the parents of the objects in one layer have different transformations this might cause an unexpected scenegraph structure since it is required to preserve the transformations.
    '''
    pass



def setFixSurfaceOrientation(fix):
    '''
    Enable orienting the normals of all surfaces, so they point in the same general direction.
    '''
    pass



def setFlushTransformations(flush):
    '''
    Enable / Disable moving transformation data of the scene graph hierarchy to the vertices. This means, that every transformation node will contain only a unit matrix.
    '''
    pass



def setImportAsSmartReference(create):
    '''
    Determine if smart references should be created for imported vpb files.
    '''
    pass



def setImportAssociativeMeshes(import_):
    '''
    Enable import of meshes associated with the surfaces.
    '''
    pass



def setImportCameras(import_):
    '''
    Enable import of cameras from CAD data. (Only Alias wire files)
    '''
    pass



def setImportCoordSystems(import_):
    '''
    Enable import of coordinate system nodes from CAD data.
    '''
    pass



def setImportCurves(import_):
    '''
    Enable import of curves and poly lines from CAD files.
    '''
    pass



def setImportEmptyLayers(import_):
    '''
    Enable import of empty leyers. (Only Alias wire files)
    '''
    pass



def setImportInvisibleCurves(import_):
    '''
    Enable import of curves and poly lines, that are invisible in the CAD data.
    '''
    pass



def setImportInvisibleInstances(import_):
    '''
    Enable import of invisible instance nodes instead of excluding them.
    '''
    pass



def setImportInvisibleMeshes(import_):
    '''
    Enable import of polygon meshes, that are invisible in the CAD file.
    '''
    pass



def setImportInvisibleSurfaces(import_):
    '''
    Enable import of NURBS surfaces, that are invisible in the CAD file.
    '''
    pass



def setImportLights(import_):
    '''
    Enable import of light sources from CAD data. (Only Alias wire files)
    '''
    pass



def setImportMeshes(import_):
    '''
    Enable import of polygon meshes.
    '''
    pass



def setImportMeshLODs(lodOption):
    '''
    Select which mesh LODs should be imported.
    '''
    pass



def setImportReferencedFiles(import_):
    '''
    Enable import of part files referenced by an assembly. If option is disabled a file reference node is created that can be used to import the referenced part later.
    '''
    pass



def setImportSurfaces(import_):
    '''
    Enable import of NURBS surfaces.
    '''
    pass



def setImportTemplateGeometries(import_):
    '''
    Enable import of template geometries instead of excluding them. (Only Alias wire files)
    '''
    pass



def setImportVariants(import_):
    '''
    Enable import of variants from CAD data. (Only Alias wire files)
    '''
    pass



def setJtToolkit(toolkit):
    '''
    Select which Jt toolkit should be used for import.
    '''
    pass



def setKeepNurbs(keep):
    '''
    Enable / disable keeping NURBS data instead of deleting it. This option will increase memory usage.
    '''
    pass



def setMaxChordLength(chordLength):
    '''
    Set maximum length of a triangle edge in mm. Lower values result in more accurate polygon models but also increase the number of triangles.
    '''
    pass



def setMergeGeometries(merge):
    '''
    Enable / disable merging adjacent surfaces with same material into shells.
    '''
    pass



def setMergeSubReferenceMaterials(optimize):
    '''
    Determine if duplicate materials, referenced in different files, should be merged into one single material. Materials with same name and identical properties are regarded as duplicates.
    '''
    pass



def setNormalTolerance(tolerance):
    '''
    Set the normal tolerance of adjacent triangles in degrees. Lower values result in more accurate polygon models but also increase the number of triangles.
    '''
    pass



def setReduceKeyframes(reduce):
    '''
    Enable reducing the number of keyframes by removing adjacent keyframes with identical value.
    '''
    pass



def setRemoveEmptyGroups(remove):
    '''
    Enable / disable removing of groups without children.
    '''
    pass



def setSmartReferenceBehavior(behavior):
    '''
    Determine how references to VRED native files are treated in import.
    '''
    pass



def setSourceReferenceBehavior(behavior):
    '''
    Determine how references to files of import file types are treated in import.
    '''
    pass



def setStitchingTolerance(tolerance):
    '''
    Set tolerance in mm where two adjacent edges are considered to be touching and where they should be stitched together.
    '''
    pass



def setUnshareNodes(unshare):
    '''
    Enable / Disable conversion of shared node instances to independent nodes.
    '''
    pass



def setUseLegacyLoader(useLegacy):
    '''
    Use legacy importer. Enabling this option is not recommended since the legacy importers only support quite old file versions and a reduced feature set. Legacy importer are only available for JT and Rhino files.
    '''
    pass



def setUseStitching(stitch):
    '''
    Enable / disable stitching of adjacent edges.
    '''
    pass



def vrdAtfSettings():
    '''
    Default constructor.
    '''
    pass



def vrdAtfSettings():
    '''
    Documentation missing
    '''
    pass


