'''
vrdAnnotationNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Returns the label background color.
'''

from typing import List


class vrdNode():
    pass


class QVector3D():
    pass


class QColor():
    pass


def getBackgroundColor() -> QColor:
    '''
    Returns the label background color.
    '''
    return None


def getFarScaleLimit():
    '''
    Documentation missing
    '''
    pass


def getFontColor() -> QColor:
    '''
    Returns the font color for the displayed text.
    '''
    return None


def getLineColor() -> QColor:
    '''
    Returns the line color for border and leader.
    '''
    return None


def getNearScaleLimit():
    '''
    Documentation missing
    '''
    pass


def getPosition() -> QVector3D:
    '''
    Returns the position as a 3D world coordinate.
    '''
    return None


def getSceneNode():
    '''
    Documentation missing
    '''
    pass


def getSize():
    '''
    Documentation missing
    '''
    pass


def getText() -> str:
    '''
    Returns the displayed description text.
    '''
    return None


def getUseSceneNodeVisibility() -> bool:
    '''
    Returns if a scene graph node is used for determining the visibility.
    '''
    return None


def setBackgroundColor(color: QColor):
    '''
    Sets the label background color (linear RGB) and opacity (alpha).
    '''
    pass


def setFarScaleLimit(value: float):
    '''
    Sets the far scaling limit. The value is used for scaling the size dynamically depending on the camera position.
    '''
    pass


def setFontColor(color: QColor):
    '''
    Sets the font color for the displayed text (linear RGB).
    '''
    pass


def setLineColor(color: QColor):
    '''
    Sets the line color for border and leader (linear RGB).
    '''
    pass


def setNearScaleLimit(value: float):
    '''
    Sets the near scaling limit. The value is used for scaling the size dynamically depending on the camera position.
    '''
    pass


def setPosition(worldPosition: QVector3D):
    '''
    The point (3D world coordinates) to which the leader arrow head is pointing.
    '''
    pass


def setSceneNode(node: vrdNode):
    '''
    Sets the linked scene graph node (see         vrdAnnotationNode.setUseSceneNodeVisibility(enabled)).
    '''
    pass


def setSize(size: float):
    '''
    Sets the size.
    '''
    pass


def setText(text: str):
    '''
    The displayed description text.
    '''
    pass


def setUseSceneNodeVisibility(enabled: bool):
    '''
    Toggles the use of the linked scene graph node to determine the visiblity. A set linked scene node is necessary (see         vrdAnnotationNode.setSceneNode(node)).
    '''
    pass


def zoomTo():
    '''
    Lets the camera of the current render window zoom to this annotation.
    '''
    pass

