'''
Autogenerated Method-Stub for:
module vrdBaseLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getCastShadowOnShadowMaterial():
    '''
    Returns if the light casts a shadow on the shadow material.
    '''
    pass



def getDiffuseColor():
    '''
    Returns the diffuse color of the light.
    '''
    pass



def getGlossyColor():
    '''
    Returns the light’s glossy color.
    '''
    pass



def getGroundShadowIntensity():
    '''
    Returns the intensity of shadows on the shadow material.
    '''
    pass



def getIlluminateShadowMaterial():
    '''
    Returns whether the light illuminates the shadow material.
    '''
    pass



def getImportanceMultiplier():
    '''
    Returns the importance multiplier of the light.
    '''
    pass



def getIntensity():
    '''
    Returns the intensity of the light.
    '''
    pass



def getIsPhysicallyBased():
    '''
    Returns whether the light source is physically based.
    '''
    pass



def getLightTransform():
    '''
    Returns the light transform.
    '''
    pass



def getLightUnit():
    '''
    Returns the unit used for this light source.
    '''
    pass



def getMaterialShadowIntensity():
    '''
    Returns the intensity of shadows of brdf based materials.
    '''
    pass



def getOn():
    '''
    Returns the state of the light.
    '''
    pass



def getTemperature():
    '''
    Returns the light temperature.
    '''
    pass



def getUseLightTemperature():
    '''
    Returns whether the light uses the temperature value to determine its color.
    '''
    pass



def getVisualizationVisible():
    '''
    Returns whether the light source visualization is visible.
    '''
    pass



def setCastShadowOnShadowMaterial(castShadow):
    '''
    Set whether the light casts a shadow on the shadow material or not.
    '''
    pass



def setDiffuseColor(diffuseColor):
    '''
    Sets the diffuse color of the light.
    '''
    pass



def setGlossyColor(glossyColor):
    '''
    Sets the glossy color of the light.
    '''
    pass



def setGroundShadowIntensity(intensity):
    '''
    Sets the intensity of shadows on the shadow material.
    '''
    pass



def setIlluminateShadowMaterial(illuminateShadosMeterial):
    '''
    Sets whether the light illuminates the shadow material.
    '''
    pass



def setImportanceMultiplier(importanceMultiplier):
    '''
    Sets the importance multiplier of the light.
    '''
    pass



def setIntensity(intensity):
    '''
    Sets the intensity of the light.
    '''
    pass



def setIsPhysicallyBased(on):
    '''
    Sets whether the light source is physically based.
    '''
    pass



def setLightUnit(unit):
    '''
    Sets the unit used for this light source.
    '''
    pass



def setMaterialShadowIntensity(intensity):
    '''
    Sets the intensity of shadows of brdf based materials.
    '''
    pass



def setOn(on):
    '''
    Switch the light on / off.
    '''
    pass



def setTemperature(kelvin):
    '''
    Sets the light temperature.
    '''
    pass



def setUseLightTemperature(use):
    '''
    Sets whether the light uses the temperature value to determine its color.
    '''
    pass



def setVisualizationVisible(showVisualization):
    '''
    Sets whether the light source visualization is visible.
    '''
    pass


