'''
Autogenerated Method-Stub for:
module vrdCameraTrackNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getFadeInDuration():
    '''
    Returns the fade in duration of the camera track.
    '''
    pass



def getPauseDuration():
    '''
    Returns the pause duration of the camera track.
    '''
    pass



def getPlaying():
    '''
    Returns the playback state of the camera track.
    '''
    pass



def getTransitionDuration():
    '''
    Returns the transition duration of the camera track.
    '''
    pass



def getType():
    '''
    Returns the type of the camera track.
    '''
    pass



def getViewpoint(index):
    '''
    Returns a viewpoint node by index.
    '''
    pass



def getViewpointCount():
    '''
    Returns the number of viewpoints belonging to this camera track node.
    '''
    pass



def getViewpoints():
    '''
    Returns all viewpoints belonging to this camera track node.
    '''
    pass



def isRenderQueueCameraTrack():
    '''
    Check if the camera track is of type RenderQueue.
    '''
    pass



def isVariantSetCameraTrack():
    '''
    Check if the camera track is of type VariantSet.
    '''
    pass



def setFadeInDuration(duration):
    '''
    Sets the fade in duration of the camera track.
    '''
    pass



def setPauseDuration(duration):
    '''
    Sets the pause duration of the camera track.
    '''
    pass



def setPlaying(playing):
    '''
    Start / stop playback of the camera track.
    '''
    pass



def setTransitionDuration(duration):
    '''
    Sets the transition duration of the camera track.
    '''
    pass


