'''
vrdConstraintNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class serves as a base class for vrdPositionConstraint, vrdOrientationConstraint and vrdAimConstraint. It gives base access to a constraint object in VRED.
'''

from typing import List


class vrdNode():
    pass


def clearConstrainedNode():
    '''
    Clears the constrained object node.
    '''
    pass


def clearTargetNodes():
    '''
    Clears the set target nodes of the constraint.
    '''
    pass


def getConstrainedNode() -> vrdNode:
    '''
    Returns the node set as the constrained object.
    '''
    return None


def getTargetNodes() -> List[vrdNode]:
    '''
    Returns the list of nodes set as targets for the constraint.
    '''
    return None


def getTargetNodeWeight(node: vrdNode) -> float:
    '''
    Gets the weight for a target node of the constraint. The node must be referenced in the target nodes list of the constraint.
    '''
    return None


def isActive() -> bool:
    '''
    Returns if the constraint is active.
    '''
    return None


def setActive(value: bool):
    '''
    Sets the constraint active/deactive.
    '''
    pass


def setConstrainedNode(node: vrdNode):
    '''
    Sets a node as the constrained object.
    '''
    pass


def setTargetNodes(nodes: List[vrdNode]):
    '''
    Sets a list of nodes as targets for the constraint.
    '''
    pass


def setTargetNodeWeight(node: vrdNode, weight: float):
    '''
    Sets the weight for a target node of the constraint. The node must be referenced in the target nodes list of the constraint.
    '''
    pass

