'''
vrdCameraTrackNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class represents a camera track node.
'''

from typing import List


class integer():
    pass


class vrdViewpointNode():
    pass


class CameraTrackType():
    pass


def getFadeInDuration() -> float:
    '''
    Returns the fade in duration of the camera track.
    '''
    return None


def getPauseDuration() -> float:
    '''
    Returns the pause duration of the camera track.
    '''
    return None


def getPlaying() -> bool:
    '''
    Returns the playback state of the camera track.
    '''
    return None


def getTransitionDuration() -> float:
    '''
    Returns the transition duration of the camera track.
    '''
    return None


def getType() -> CameraTrackType:
    '''
    Returns the type of the camera track.
    '''
    return None


def getViewpoint(index: integer) -> vrdViewpointNode:
    '''
    Returns a viewpoint node by index.
    '''
    return None


def getViewpointCount() -> integer:
    '''
    Returns the number of viewpoints belonging to this camera track node.
    '''
    return None


def getViewpoints() -> List[vrdViewpointNode]:
    '''
    Returns all viewpoints belonging to this camera track node.
    '''
    return None


def isRenderQueueCameraTrack() -> bool:
    '''
    Check if the camera track is of type RenderQueue.
    '''
    return None


def isVariantSetCameraTrack() -> bool:
    '''
    Check if the camera track is of type VariantSet.
    '''
    return None


def setFadeInDuration(duration: float):
    '''
    Sets the fade in duration of the camera track.
    '''
    pass


def setPauseDuration(duration: float):
    '''
    Sets the pause duration of the camera track.
    '''
    pass


def setPlaying(playing: bool):
    '''
    Start / stop playback of the camera track.
    '''
    pass


def setTransitionDuration(duration: float):
    '''
    Sets the transition duration of the camera track.
    '''
    pass

