'''
Autogenerated Method-Stub for:
module vrdDirectionalLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getIsHeadLight():
    '''
    Returns whether this light source is the head light node.
    '''
    pass


