'''
Autogenerated Method-Stub for:
module vrdDiskLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAreaLightCone():
    '''
    Returns the area light cone.
    '''
    pass


