'''
vrdDeltaLightNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This is the base class for all delta light types.
'''

from typing import List


class vrdShadowMap():
    pass


def getIlluminateScene() -> bool:
    '''
    Returns whether the light illuminates the scene.
    '''
    return None


def getLocalLight() -> bool:
    '''
    Returns if this light is a local light.
    '''
    return None


def getShadowMap() -> vrdShadowMap:
    '''
    Returns the shadow map of the light source.
    '''
    return None


def getVisualizationScale() -> float:
    '''
    Returns the scale of the light visualization.
    '''
    return None


def setIlluminateScene(illuminateScene: bool):
    '''
    Sets whether the light source illuminates the scene.
    '''
    pass


def setLocalLight(isLocalLight: bool):
    '''
    Sets the local light flag.
    '''
    pass


def setVisualizationScale(scale: float):
    '''
    Sets the scale of the light visualization.
    '''
    pass

