'''
vrdDeviceAction
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Represents an action that is part of an interaction.
'''

from typing import List


class string():
    pass


class vrdDeviceActionSignal():
    pass


def getName() -> string:
    '''
    Gets the name of the action.
    '''
    return None


def signal() -> vrdDeviceActionSignal:
    '''
    Gets the signal that is sent, when the action is triggered.
    '''
    return None

