'''
Autogenerated Method-Stub for:
module vrdDeviceMessageData
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getBackgroundColor():
    '''
    Documentation missing
    '''
    pass



def getFontSize():
    '''
    Documentation missing
    '''
    pass



def getForegroundColor():
    '''
    Documentation missing
    '''
    pass



def getFrameSize():
    '''
    Documentation missing
    '''
    pass



def getImageDpi():
    '''
    Documentation missing
    '''
    pass



def getImagePath():
    '''
    Documentation missing
    '''
    pass



def getPosition():
    '''
    Documentation missing
    '''
    pass



def getRotation():
    '''
    Documentation missing
    '''
    pass



def getText():
    '''
    Documentation missing
    '''
    pass



def getUseImage():
    '''
    Documentation missing
    '''
    pass



def setBackgroundColor(color):
    '''
    Set the background color for the message.
    '''
    pass



def setFontSize(value):
    '''
    Set the font size for the message text.
    '''
    pass



def setForegroundColor(color):
    '''
    Set the foreground color (e.g. text) for the message.
    '''
    pass



def setFrameSize(value):
    '''
    Set the frame size (outline width) of the message rectangle.
    '''
    pass



def setImageDpi(dpi):
    '''
    Set the dpi for the image.
    '''
    pass



def setImagePath(path):
    '''
    Set a path to an image file. See         vrdDeviceMessageData.setUseImage(value).
    '''
    pass



def setPosition(position):
    '''
    Set the position of the message.
    '''
    pass



def setRotation(eulerRotation):
    '''
    Set the orientation of the message.
    '''
    pass



def setText(text):
    '''
    Set the message text.
    '''
    pass



def setUseImage(value):
    '''
    Set if an image instead of text is used.
    '''
    pass



def vrdDeviceMessageData():
    '''
    Documentation missing
    '''
    pass



def vrdDeviceMessageData():
    '''
    Documentation missing
    '''
    pass


