'''
Autogenerated Method-Stub for:
module vrdDeviceAction
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getName():
    '''
    Gets the name of the action.
    '''
    pass



def signal():
    '''
    Gets the signal that is sent, when the action is triggered.
    '''
    pass


