'''
vrdDeviceInteraction
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Represents an interaction that can contain several     vrdDeviceAction which are triggered by controller events.
'''

from typing import List


class vrdDeviceAction():
    pass


def addSupportedInteractionGroup(name: str):
    '''
    Adds an interaction group to the supported interaction groups.
    '''
    pass


def createControllerAction(mapping: str) -> vrdDeviceAction:
    '''
    Creates an action for this interaction.
    '''
    return None


def getControllerAction(name: str) -> vrdDeviceAction:
    '''
    Gets an already existing action related to the interaction.
    '''
    return None


def getControllerActions() -> List[vrdDeviceAction]:
    '''
    Gets a list of all action objects related to the interaction.
    '''
    return None


def getName():
    '''
    Documentation missing
    '''
    pass


def getSupportedInteractionGroups():
    '''
    Documentation missing
    '''
    pass


def removeControllerAction(action: vrdDeviceAction):
    '''
    Removes an action from the interaction.
    '''
    pass


def removeSupportedInteractionGroup(name: str):
    '''
    Removes an interaction group from being supported by the interaction.
    '''
    pass


def setControllerActionMapping(actionName: str, mapping: str):
    '''
    Sets the mapping of an already existing action related to this interaction.
    '''
    pass


def setSupportedInteractionGroups(names: List[str]):
    '''
    Sets the interaction groups the interaction will be part of. Setting no groups will activate this interaction for all interaction groups.
    '''
    pass

