'''
Autogenerated Method-Stub for:
module vrdEyeGaze
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getDirection():
    '''
    Get normalized direction of the gaze ray.
    '''
    pass



def getOrigin():
    '''
    Get origin of the gaze ray.
    '''
    pass



def isTracked():
    '''
    Documentation missing
    '''
    pass



def setDirection(direction):
    '''
    Set normalized direction of the gaze ray.
    '''
    pass



def setOrigin(origin):
    '''
    Set origin of the gaze ray.
    '''
    pass



def setTracked(tracked):
    '''
    Set whether the eye gaze is tracked.
    '''
    pass



def vrdEyeGaze():
    '''
    Default constructor.
    '''
    pass



def vrdEyeGaze(state):
    '''
    Copy constructor.
    '''
    pass


