'''
vrdImmersiveMenu
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
VR menu object.
'''

from typing import List


class integer():
    pass


class MenuConstraint():
    pass


class MenuOrigin():
    pass


class QVector3D():
    pass


class string():
    pass


def attachTo(origin: integer, constraint: integer):
    '''
    Reattaches the menu.
    '''
    pass


def getConstraint():
    '''
    Documentation missing
    '''
    pass


def getDepth():
    '''
    Documentation missing
    '''
    pass


def getHeight():
    '''
    Documentation missing
    '''
    pass


def getName():
    '''
    Documentation missing
    '''
    pass


def getOrigin():
    '''
    Documentation missing
    '''
    pass


def getRotation():
    '''
    Documentation missing
    '''
    pass


def getTranslation():
    '''
    Documentation missing
    '''
    pass


def getWidth():
    '''
    Documentation missing
    '''
    pass


def isVisible():
    '''
    Documentation missing
    '''
    pass


def setConstraint(value: MenuConstraint):
    '''
    Changes the transformation constraint.
    '''
    pass


def setContent(content: string):
    '''
    Use the given string to show the content.
    '''
    pass


def setDepth(value: float):
    '''
    Sets the depth of the menu.
    '''
    pass


def setHeight(value: float):
    '''
    Sets the height of the menu.
    '''
    pass


def setModule(moduleTitle: string):
    '''
    Use the given name to find a module to be displayed on the menu.
    '''
    pass


def setName(value: string):
    '''
    Changes the name of the menu.
    '''
    pass


def setOrigin(value: MenuOrigin):
    '''
    Changes the origin for the menu.
    '''
    pass


def setRotation(rotation: QVector3D):
    '''
    Changes rotation of the menu relative to the selected origin.
    '''
    pass


def setRotation(xDeg: float, yDeg: float, zDeg: float):
    '''
    Changes rotation of the menu relative to the selected origin.
    '''
    pass


def setTranslation(position: QVector3D):
    '''
    Changes position of the menu relative to the selected origin.
    '''
    pass


def setTranslation(x: float, y: float, z: float):
    '''
    Changes position of the menu relative to the selected origin.
    '''
    pass


def setUrl(url: string, pixelWidth: integer, pixelHeight: integer):
    '''
    Use the given url to show web content on the mneu.
    '''
    pass


def setVisible(value: bool):
    '''
    Shows or hides the menu.
    '''
    pass


def setWidget():
    '''
    Documentation missing
    '''
    pass


def setWidth(value: float):
    '''
    Sets the width of the menu.
    '''
    pass

