'''
Autogenerated Method-Stub for:
module vrdImmersiveTool
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getCheckable():
    '''
    Documentation missing
    '''
    pass



def getChecked():
    '''
    Documentation missing
    '''
    pass



def getCheckedCommand():
    '''
    Documentation missing
    '''
    pass



def getClickedCommand():
    '''
    Documentation missing
    '''
    pass



def getGroup():
    '''
    Documentation missing
    '''
    pass



def getHideAway():
    '''
    Returns if the tool is hidden from the VR menu.
    '''
    pass



def getIcon():
    '''
    Documentation missing
    '''
    pass



def getIsInternal():
    '''
    Returns if the tool is marked as internal. All tools that are created internally by default will have this flag set.
    '''
    pass



def getName():
    '''
    Documentation missing
    '''
    pass



def getText():
    '''
    Documentation missing
    '''
    pass



def getUncheckedCommand():
    '''
    Documentation missing
    '''
    pass



def getViewContent():
    '''
    Documentation missing
    '''
    pass



def getViewWidget():
    '''
    Documentation missing
    '''
    pass



def hideAway(value):
    '''
    If value is True, this tool is not visible on the VR menu.
    '''
    pass



def setCheckable(value):
    '''
    Sets the tool button to checkable.
    '''
    pass



def setChecked(value):
    '''
    Sets the tool button to checked.
    '''
    pass



def setCheckedCommand(value):
    '''
    Sets the Python command that is executed when the button is checked.
    '''
    pass



def setClickedCommand(value):
    '''
    Sets the Python command that is executed on button click.
    '''
    pass



def setGroup(value):
    '''
    Changes the group in which the tool is inserted.
    '''
    pass



def setIcon(icon):
    '''
    Sets the icon displayed on the VR tools menu.
    '''
    pass



def setIconData(data, format):
    '''
    Use a base64 encoded string to set the icon.
    '''
    pass



def setIconPath(iconPath):
    '''
    Use the image at the given path as an icon.
    '''
    pass



def setOnOffIconData(onData, offData, format):
    '''
    Use two base64 encoded strings to set the icon.
    '''
    pass



def setText(text):
    '''
    Changes the text displayed on the VR tools menu.
    '''
    pass



def setUncheckedCommand(value):
    '''
    Sets the Python command that is executed when the button is unchecked.
    '''
    pass



def setViewContent(value):
    '''
    On tool button press, the given content is displayed on a menu panel.
    '''
    pass



def setViewWidget(widget):
    '''
    On tool button press, the given content is displayed on a menu panel.
    '''
    pass



def signal():
    '''
    Documentation missing
    '''
    pass


