'''
Autogenerated Method-Stub for:
module vrdImage
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAbsolutePath():
    '''
    Returns the absolute path of the image.
    '''
    pass



def getDimension():
    '''
    Gets the dimension of the image.
    '''
    pass



def getHeight():
    '''
    Gets the height of the image.
    '''
    pass



def getWidth():
    '''
    Gets the width of the image.
    '''
    pass



def hasAlphaChannel():
    '''
    Determines if the image has an alpha channel.
    '''
    pass



def toQIcon():
    '''
    Returns the image data as a QIcon.
    '''
    pass



def toQImage():
    '''
    Returns the image data as a QImage.
    '''
    pass


