'''
vrdImage
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Class that gives access to VRED’s internal image format.
'''

from typing import List


class string():
    pass


class QImage():
    pass


class QIcon():
    pass


class QSize():
    pass


def getAbsolutePath() -> string:
    '''
    Returns the absolute path of the image.
    '''
    return None


def getDimension() -> QSize:
    '''
    Gets the dimension of the image.
    '''
    return None


def getHeight() -> float:
    '''
    Gets the height of the image.
    '''
    return None


def getWidth() -> float:
    '''
    Gets the width of the image.
    '''
    return None


def hasAlphaChannel() -> bool:
    '''
    Determines if the image has an alpha channel.
    '''
    return None


def toQIcon() -> QIcon:
    '''
    Returns the image data as a QIcon.
    '''
    return None


def toQImage() -> QImage:
    '''
    Returns the image data as a QImage.
    '''
    return None

