'''
vrdLensFlareFxElement
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class is used for all common properties of     vrdLensFlareStar, vrdLensFlareGhost, vrdLensFlareStreak and vrdLensFlareGlow lens flare effect classes.
'''

from typing import List


class QVector3D():
    pass


def getColor() -> QVector3D:
    '''
    Get the color of this effect.
    '''
    return None


def getFeather() -> float:
    '''
    Get the fade out value.
    '''
    return None


def getIntensity() -> float:
    '''
    Get current intensity.
    '''
    return None


def getRotation() -> float:
    '''
    Get current used rotation value.
    '''
    return None


def getSize() -> float:
    '''
    Get the current used effect size.
    '''
    return None


def setColor(tint: QVector3D):
    '''
    Use to change the color of the lens flare. If the light already has an assigned color, this color will be mixed with it.
    '''
    pass


def setFeather(blurring: float):
    '''
    Lets the effect fade towards the edge. Value of 0.0 deactivates the effect.
    '''
    pass


def setIntensity(intensity: float):
    '''
    Makes the effect more or less intense.
    '''
    pass


def setRotation(rotation: float):
    '''
    Rotate the effect on light ray axis.
    '''
    pass


def setSize(size: float):
    '''
    Set the effect size, must be positive.
    '''
    pass

