'''
Autogenerated Method-Stub for:
module vrdLensFlareElement
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getIsActive():
    '''
    Returns activation state of the lens flare element.
    '''
    pass



def getName():
    '''
    Returns name of this lens flare element.
    '''
    pass



def setIsActive(active):
    '''
    Each lens flare element can be inactive for a while. The element will be hidden if is inactive. This method set the activation state of a lens flare element.
    '''
    pass



def setName(name):
    '''
    Each lens flare has a name. The name must not be unique. This method set the name.
    '''
    pass


