'''
Autogenerated Method-Stub for:
module vrdLensFlareGhostLine
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createGhost(distance):
    '''
    A new ghost will be created for this line. The new ghost object has default properties. A ‘ghost’ property signal is emitted for the line object.
    '''
    pass



def getGhosts():
    '''
    Get a list of all ghost of this line.
    '''
    pass



def removeGhosts(ghosts):
    '''
    Remove some ghosts of this line. It will be checked, if the given ghosts are in this line. A ‘ghost’ property signal is emitted for the line object. But this only happens when ghosts have been removed. If the parameter list was empty, the signal is not sent. If the ghosts were not in this line, the signal will not be sent either.
    '''
    pass


