'''
Autogenerated Method-Stub for:
module vrdLensFlareStar
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getImage():
    '''
    Return the current used texture.
    '''
    pass



def getNumberOfBursts():
    '''
    Get how many arms a Starburst element has.
    '''
    pass



def getShape():
    '''
    Get the current used shape.
    '''
    pass



def getThickness():
    '''
    Get the current used thickness of the effect.
    '''
    pass



def setImage(image):
    '''
    Set an image for this element. You has to change the type to Texture to use the image for the star effect.
    '''
    pass



def setNumberOfBursts(numberOfBursts):
    '''
    Use to set how many arms a Starburst element has.
    '''
    pass



def setShape(shape):
    '''
    Change its current shape to a fan, spike, blade, or texture.
    '''
    pass



def setThickness(thickness):
    '''
    Controls the thickness of the effect.
    '''
    pass


