'''
Autogenerated Method-Stub for:
module vrdLensFlareStreak
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getOffset():
    '''
    Get offset the streak effect from the center of the light source.
    '''
    pass



def getThickness():
    '''
    Get the current used thickness of the effect.
    '''
    pass



def setOffset(offset):
    '''
    Use to offset the streak effect from the center of the light source. Negative values will move the streak to the left and below the light. Positive will move it to the right and above the light.
    '''
    pass



def setThickness(thickness):
    '''
    Controls the thickness of the effect.
    '''
    pass


