'''
vrdLensFlareStreak
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class is used for a streaking effect, like what you get when using an anamorphic lens. Use it for things such as street lamps at night, objects with stationary lights, or a light source that’s partially obscured by an object, like a tree or building’s edge. A short introduction can be found under     https://help.autodesk.com/view/VREDPRODUCTS/2020/ENU/?guid=VRED_Lights_About_Lens_Flares_and_Elements_html.
'''

from typing import List


class QVector2D():
    pass


def getOffset() -> QVector2D:
    '''
    Get offset the streak effect from the center of the light source.
    '''
    return None


def getThickness() -> float:
    '''
    Get the current used thickness of the effect.
    '''
    return None


def setOffset(offset: QVector2D):
    '''
    Use to offset the streak effect from the center of the light source. Negative values will move the streak to the left and below the light. Positive will move it to the right and above the light.
    '''
    pass


def setThickness(thickness: float):
    '''
    Controls the thickness of the effect.
    '''
    pass

