'''
Autogenerated Method-Stub for:
module vrdLensFlareFxElement
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getColor():
    '''
    Get the color of this effect.
    '''
    pass



def getFeather():
    '''
    Get the fade out value.
    '''
    pass



def getIntensity():
    '''
    Get current intensity.
    '''
    pass



def getRotation():
    '''
    Get current used rotation value.
    '''
    pass



def getSize():
    '''
    Get the current used effect size.
    '''
    pass



def setColor(tint):
    '''
    Use to change the color of the lens flare. If the light already has an assigned color, this color will be mixed with it.
    '''
    pass



def setFeather(blurring):
    '''
    Lets the effect fade towards the edge. Value of 0.0 deactivates the effect.
    '''
    pass



def setIntensity(intensity):
    '''
    Makes the effect more or less intense.
    '''
    pass



def setRotation(rotation):
    '''
    Rotate the effect on light ray axis.
    '''
    pass



def setSize(size):
    '''
    Set the effect size, must be positive.
    '''
    pass


