'''
Autogenerated Method-Stub for:
module vrdLensFlareEffect
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createLensFlareElement(name, type):
    '''
    
    '''
    pass



def getAngularIntensity():
    '''
    Returns the angular intensity.
    '''
    pass



def getColor():
    '''
    Returns the lens flare color.
    '''
    pass



def getIntensity():
    '''
    Returns the brightness of all lens flares.
    '''
    pass



def getIsActive():
    '''
    Returns if the lens flare effect is enabled.
    '''
    pass



def getLensFlareElements():
    '''
    Documentation missing
    '''
    pass



def getPresetType():
    '''
    Documentation missing
    '''
    pass



def getRadius():
    '''
    Returns the radius.
    '''
    pass



def getSize():
    '''
    Returns the size of all lens flares.
    '''
    pass



def getUseLightProperties():
    '''
    Returns if the intensity of the light is used.
    '''
    pass



def removeElements():
    '''
    Documentation missing
    '''
    pass



def setAngularIntensity(angularIntensity):
    '''
    Changes the brightness of the flare, as the angle changes. As the light source is rotated toward the viewer, becoming perpendicular to the view, its intensity increases. It is like how intense a sunset gets as it reaches the horizon, just before setting. Another example would be turning a flashlight’s beam toward you. From your point of view, as the light aligns with your view, it becomes more intense, to the point of blinding.
    '''
    pass



def setColor(color):
    '''
    Sets the color of all lens flares. The color is multiplied with any element color already assigned. Note: If Use Light Properties is enabled, the color set here is ignored and the light color is used. Note: Since this color is multiplied with element color assignments, there may be instances where a lens flare disappears, due to the multiply operation. If this occurs, try changing the color of the individual lens flares (instead of using this option) or change the color of this option. If there are no element assigned colors, this color is assigned to all lens flares.
    '''
    pass



def setIntensity(intensity):
    '''
    Changes the brightness of all lens flares.
    '''
    pass



def setIsActive(active):
    '''
    Enables or disables the lens flare effect.
    '''
    pass



def setPresetType():
    '''
    Documentation missing
    '''
    pass



def setRadius(radius):
    '''
    Changes how dispersed the flare is for all lens flares. The radius represents the virtual size of the light sources, since the lights do not have geometry. A larger radius requires a larger object to completely occlude the effect. Shrinking of the lens flare will start when the radius around the light source starts to get occluded by an object. That occlusion also decreases the intensity of the ghosts. As the radius increases, the intensity of the light decreases. As the radius decreases, the flare becomes more intense and defined.
    '''
    pass



def setSize(size):
    '''
    Changes the size of all lens flares.
    '''
    pass



def setUseLightProperties(use):
    '''
    Use the intensity of the light settings instead of the local setting. This only affects the color. When disabled, the local color is used.
    '''
    pass


