'''
Autogenerated Method-Stub for:
module vrdLightTexture
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAnisotropy():
    '''
    Returns the anisotropy value of the texture.
    '''
    pass



def getConnectRepeatModes():
    '''
    Returns whether the repeat modes for U and V are connected.
    '''
    pass



def getFrameOffset():
    '''
    Returns the offset to the image number when using an image sequence.
    '''
    pass



def getImage(void_parameter):
    '''
    Returns the image that is used as a texture.
    '''
    pass



def getInlineImageSequence():
    '''
    Returns if the image sequence is inlined into the vpb file.
    '''
    pass



def getOffset(void_parameter):
    '''
    Returns the offset for the UVs.
    '''
    pass



def getRepeat(void_parameter):
    '''
    Returns the number of repetitions for the UVs.
    '''
    pass



def getRepeatModeU(void_parameter):
    '''
    Returns the repeat mode of the texture.
    '''
    pass



def getRepeatModeV(void_parameter):
    '''
    Returns the repeat mode of the texture.
    '''
    pass



def getRotate(void_parameter):
    '''
    Returns the texture rotation.
    '''
    pass



def getUseImageSequence():
    '''
    Returns if image sequences is used.
    '''
    pass



def getUseTexture(void_parameter):
    '''
    Returns whether the light texture is enabled.
    '''
    pass



def setAnisotropy(anisotropy):
    '''
    Sets the anisotropy value of the texture.
    '''
    pass



def setConnectRepeatModes(connected):
    '''
    Connects the repeat modes for U and V.
    '''
    pass



def setFrameOffset(offset):
    '''
    Sets an offset to the image number when using an image sequence.
    '''
    pass



def setImage(img):
    '''
    Sets the image that should be used as a texture.
    '''
    pass



def setInlineImageSequence(use):
    '''
    Inlines the image sequence into the vpb file.
    '''
    pass



def setOffset(offset):
    '''
    Sets the offset for the UVs.
    '''
    pass



def setRepeat(repeat):
    '''
    Sets the number of repetitions for the UVs.
    '''
    pass



def setRepeatModeU(mode):
    '''
    Sets the repeat mode of the texture.
    '''
    pass



def setRepeatModeV(mode):
    '''
    Sets the repeat mode of the texture.
    '''
    pass



def setRotate(rotate):
    '''
    Rotate the texture.
    '''
    pass



def setUseImageSequence(use):
    '''
    Use an image sequence.
    '''
    pass



def setUseTexture(s):
    '''
    Enables / disables the usage of the texture.
    '''
    pass


