'''
vrdLensFlareRing
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Get used chromatic aberration values as RGB.
'''

from typing import List


class integer():
    pass


class QVector3D():
    pass


def getChromaticAberration() -> QVector3D:
    '''
    Get used chromatic aberration values as RGB.
    '''
    return None


def getIsChromaticAberrationActive() -> bool:
    '''
    Get activation state the usage of chromatic aberration.
    '''
    return None


def getNumberOfStreaks() -> integer:
    '''
    Get how many arms a Ring element has.
    '''
    return None


def getStreakThickness() -> float:
    '''
    Get the thickness of the segments.
    '''
    return None


def getThickness() -> float:
    '''
    Get the current used thickness of the effect.
    '''
    return None


def setChromaticAberration(chromaticAberration: QVector3D):
    '''
    Use chromatic aberration with the lens flare element to distort the colors.
    '''
    pass


def setIsChromaticAberrationActive(isActive: bool):
    '''
    Activate the usage of chromatic aberration.
    '''
    pass


def setNumberOfStreaks(numberOfStreaks: integer):
    '''
    Use to set how many arms a Ring element has.
    '''
    pass


def setStreakThickness(streakThickness: float):
    '''
    Controls the thickness of the segments.
    '''
    pass


def setThickness(thickness: float):
    '''
    Controls the thickness of the effect.
    '''
    pass

