'''
vrdObject
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Returns the internal object id.
'''

from typing import List


def getObjectId() -> int:
    '''
    Returns the internal object id.
    '''
    return None


def isNull() -> bool:
    '''
    Determines if the object is null.
    '''
    return None

