'''
Autogenerated Method-Stub for:
module vrdPointLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAttenuation():
    '''
    Returns the falloff of the light intensity.
    '''
    pass



def getLensFlareEffect():
    '''
    Returns the lens flare effect.
    '''
    pass



def getLightProfile():
    '''
    Returns the light profile.
    '''
    pass



def getTexture():
    '''
    Returns the light texture.
    '''
    pass



def setAttenuation(attenuation):
    '''
    Sets the falloff of the light intensity.
    '''
    pass


