'''
vrdRayFileInfo
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Interface to ray files.
'''

from typing import List


class string():
    pass


class integer():
    pass


def getLuminousPower():
    '''
    Documentation missing
    '''
    pass


def getNumberOfRays():
    '''
    Documentation missing
    '''
    pass


def getScalingFactor():
    '''
    Documentation missing
    '''
    pass


def getSpectralInformationString():
    '''
    Documentation missing
    '''
    pass


def vrdRayFileInfo(luminousPower: float, numberOfRays: integer, scalingFactor: float, spectralInformationString: string):
    '''
    Create a ray file information object. In general this is not created by the user but returned by a         vrdRayFile to provide information about the used ray file.
    '''
    pass


def vrdRayFileInfo():
    '''
    Documentation missing
    '''
    pass


def vrdRayFileInfo():
    '''
    Documentation missing
    '''
    pass

