'''
vrdRectangularLightNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class represents a Rectangular light.
'''

from typing import List


class vrdAreaLightCone():
    pass


def getAreaLightCone() -> vrdAreaLightCone:
    '''
    Returns the area light cone.
    '''
    return None

