'''
Autogenerated Method-Stub for:
module vrdSceneplateNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getBackgroundColor():
    '''
    Returns the text background color.
    '''
    pass



def getBackgroundTransparency():
    '''
    Returns the transparency of the text background.
    '''
    pass



def getBrightness():
    '''
    Returns brightness from color correction.
    '''
    pass



def getClickThrough():
    '''
    Returns the transparency limit for content to be unnoticeable to mouse clicks.
    '''
    pass



def getContentType():
    '''
    Returns the type of content to be displayed on the plate.
    '''
    pass



def getContrast():
    '''
    Returns contrast from color correction.
    '''
    pass



def getFont():
    '''
    Returns font name.
    '''
    pass



def getFontColor():
    '''
    Returns the font color.
    '''
    pass



def getFontHeight():
    '''
    Returns the vertical resolution in pixels per text line.
    '''
    pass



def getFontStyle():
    '''
    Returns text font style.
    '''
    pass



def getFrameOffset():
    '''
    Returns offset to the image number when using an image sequence.
    '''
    pass



def getHeight():
    '''
    Returns the height of the canvas in pixels for HTML content.
    '''
    pass



def getHueShift():
    '''
    Returns hue shift from color correction.
    '''
    pass



def getImage():
    '''
    Returns the image object.
    '''
    pass



def getImageNumber():
    '''
    Returns image number in current image sequence.
    '''
    pass



def getInlineImageSequence():
    '''
    Returns if image sequence is inlined into the vpb file.
    '''
    pass



def getNodeType():
    '''
    Returns the node type.
    '''
    pass



def getOffset():
    '''
    Returns the offset of the plate to its anchor point.
    '''
    pass



def getOffsetMode():
    '''
    Returns how offset should be interpreted. Absolute means the offset is in pixels. Relative means the offset is given as a fraction of the viewport extents.
    '''
    pass



def getPosition():
    '''
    Returns the anchor point of the plate within the viewport.
    '''
    pass



def getRepeatMode():
    '''
    Returns the repeat mode of the plate image within the viewport.
    '''
    pass



def getRotation():
    '''
    Returns the amount the plate is rotated clockwise in degrees around its center.
    '''
    pass



def getSaturation():
    '''
    Returns saturation from color correction.
    '''
    pass



def getSize():
    '''
    Returns the height of the plate.
    '''
    pass



def getSizeMode():
    '''
    Returns how size is interpreted. Absolute means the size is in pixels. Relative means the size is a fraction of the viewport height.
    '''
    pass



def getText():
    '''
    Returns the text.
    '''
    pass



def getTransparency():
    '''
    Returns the overall transparency of the plate.
    '''
    pass



def getUrl():
    '''
    Returns the url or the content of a web site.
    '''
    pass



def getUseImageSequence():
    '''
    Returns if image sequences is used.
    '''
    pass



def getWhiteBalance():
    '''
    Returns white balance from color correction.
    '''
    pass



def getWidth():
    '''
    Returns the width of the canvas in pixels for HTML content.
    '''
    pass



def setBackgroundColor(color):
    '''
    Sets the text background color.
    '''
    pass



def setBackgroundTransparency(transparency):
    '''
    Sets the transparency of the text background.
    '''
    pass



def setBrightness(brightness):
    '''
    Shifts the content’s blacks, grays, and whites. Higher values increase the perceived luminance of the content.
    '''
    pass



def setClickThrough(clickThrough):
    '''
    Sets the transparency limit for content to be unnoticeable to mouse clicks.
    '''
    pass



def setContentType(contentType):
    '''
    Sets the type of content to be displayed on the plate.
    '''
    pass



def setContrast(contrast):
    '''
    Shifts the content’s light and dark color values. Higher values create brighter highlights and darker shadows.
    '''
    pass



def setFont(fontName):
    '''
    Sets the text font.
    '''
    pass



def setFontColor(color):
    '''
    Sets the text color.
    '''
    pass



def setFontHeight(fontHeight):
    '''
    Sets the vertical resolution in pixels per text line.
    '''
    pass



def setFontStyle(style):
    '''
    Sets text font style.
    '''
    pass



def setFrameOffset(frameOffset):
    '''
    Sets an offset to the image number when using an image sequence.
    '''
    pass



def setHeight(height):
    '''
    Sets the height of the canvas in pixels for HTML content.
    '''
    pass



def setHueShift(value):
    '''
    Shifts all content colors uniformly through the hue color range.
    '''
    pass



def setImage(img):
    '''
    Sets image object.
    '''
    pass



def setImageNumber(imageNumber):
    '''
    Sets the image number in current image sequence.
    '''
    pass



def setInlineImageSequence(inlineImageSequence):
    '''
    Inlines the image sequence into the vpb file.
    '''
    pass



def setNodeType(nodeType):
    '''
    Sets the sceneplate type. Frontplates appear on top of the scene and backplates behind.
    '''
    pass



def setOffset(offset):
    '''
    Sets the offset of the plate to its anchor point.
    '''
    pass



def setOffsetMode(offsetMode):
    '''
    Sets how offset should be interpreted. Absolute means the offset is in pixels. Relative means the offset is given as a fraction of the viewport extents.
    '''
    pass



def setPosition(position):
    '''
    Sets the anchor point of the plate within the viewport.
    '''
    pass



def setRepeatMode(repeatMode):
    '''
    Sets the repeat mode of the plate image within the viewport.
    '''
    pass



def setRotation(rotation):
    '''
    Sets the amount the plate is rotated clockwise in degrees around its center.
    '''
    pass



def setSaturation(saturation):
    '''
    Shifts the content’s color intensity. Higher values produce vivid colors. Lower values produce dull grayer colors.
    '''
    pass



def setSize(size):
    '''
    Sets the height of the plate. Width is set accordingly to maintain the aspect ratio of its content.
    '''
    pass



def setSizeMode(sizeMode):
    '''
    Sets how size is interpreted. Absolute means the size is in pixels. Relative means the size is a fraction of the viewport height.
    '''
    pass



def setText(text):
    '''
    Sets the text.
    '''
    pass



def setTransparency(transparency):
    '''
    Sets the overall transparency of the plate.
    '''
    pass



def setUrl(url):
    '''
    The url can contain a valid URL to a website (‘        http://www.autodesk.com’) or the html content of a website as a string.
    '''
    pass



def setUseImageSequence(useImageSequence):
    '''
    Use an image sequence.
    '''
    pass



def setWhiteBalance(whiteBalance):
    '''
    Shifts the content’s white balance to match the color temperature of the scene in Kelvin. Lower values produce cooler (bluish) colors. Higher values produce warmer (yellowish) colors.
    '''
    pass



def setWidth(width):
    '''
    Sets the width of the canvas in pixels for HTML content.
    '''
    pass


