'''
Autogenerated Method-Stub for:
module vrdSpotLightNode
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getConeAngle():
    '''
    Returns the light beam’s angle from center to the edge, measured in degrees.
    '''
    pass



def getPenumbraAngle():
    '''
    Returns the light edge’s falloff in degrees.
    '''
    pass



def setConeAngle(angle):
    '''
    Sets the light beam’s angle from center to the edge, measured in degrees.
    '''
    pass



def setPenumbraAngle(angle):
    '''
    Sets the light edge’s falloff in degrees.
    '''
    pass


