'''
vrdShadowMap
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
This class represents a shadow map used in OpenGL rendering.
'''

from typing import List


def getFilterRadius() -> float:
    '''
    Returns the radius used for shadow map filtering.
    '''
    return None


def getResolution() -> int:
    '''
    Returns the resolution of the shadow map.
    '''
    return None


def setFilterRadius(radius: float):
    '''
    Sets the radius for shadow map filtering.
    '''
    pass


def setResolution(resolution: int):
    '''
    Sets the resolution of the shadow map.
    '''
    pass

