'''
vrdSpotLightNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Returns the light beam’s angle from center to the edge, measured in degrees.
'''

from typing import List


def getConeAngle() -> float:
    '''
    Returns the light beam’s angle from center to the edge, measured in degrees.
    '''
    return None


def getPenumbraAngle() -> float:
    '''
    Returns the light edge’s falloff in degrees.
    '''
    return None


def setConeAngle(angle: float):
    '''
    Sets the light beam’s angle from center to the edge, measured in degrees.
    '''
    pass


def setPenumbraAngle(angle: float):
    '''
    Sets the light edge’s falloff in degrees.
    '''
    pass

