'''
vrdSwitchNode
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Returns the current choice
'''

from typing import List


class integer():
    pass


def getChoice() -> integer:
    '''
    Returns the current choice
    '''
    return None


def setChoice(choice: integer):
    '''
    Set the choice.
    '''
    pass

