'''
Autogenerated Method-Stub for:
module vrdSessionUser
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getCameraMatrix():
    '''
    Documentation missing
    '''
    pass



def getDeviceImage():
    '''
    Documentation missing
    '''
    pass



def getDeviceName():
    '''
    Documentation missing
    '''
    pass



def getHasLeftHand():
    '''
    Documentation missing
    '''
    pass



def getHasRightHand():
    '''
    Documentation missing
    '''
    pass



def getHeadNode():
    '''
    Documentation missing
    '''
    pass



def getHeadTrackingMatrix():
    '''
    Documentation missing
    '''
    pass



def getIsHmd():
    '''
    Documentation missing
    '''
    pass



def getIsRemote():
    '''
    Documentation missing
    '''
    pass



def getLeftHandNode():
    '''
    Documentation missing
    '''
    pass



def getLeftHandTrackingMatrix():
    '''
    Documentation missing
    '''
    pass



def getProjectCRC():
    '''
    Documentation missing
    '''
    pass



def getProjectName():
    '''
    Documentation missing
    '''
    pass



def getRightHandNode():
    '''
    Documentation missing
    '''
    pass



def getRightHandTrackingMatrix():
    '''
    Documentation missing
    '''
    pass



def getRoom():
    '''
    Documentation missing
    '''
    pass



def getSpectatorCount():
    '''
    Documentation missing
    '''
    pass



def getTorsoNode():
    '''
    Documentation missing
    '''
    pass



def getUserColor():
    '''
    Documentation missing
    '''
    pass



def getUserIcon():
    '''
    Documentation missing
    '''
    pass



def getUserId():
    '''
    Documentation missing
    '''
    pass



def getUserName():
    '''
    Documentation missing
    '''
    pass



def sendPython(command, commandId):
    '''
    Sends a python command to this users.
    '''
    pass


