'''
Autogenerated Method-Stub for:
module vrdTurntable
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getAngle():
    '''
    Returns the angle of the turntable/.
    '''
    pass



def getAnimationDuration():
    '''
    Returns the duration of the turntable animation.
    '''
    pass



def getDirection():
    '''
    Returns the turntable animation playback direction.
    '''
    pass



def getDistance():
    '''
    Returns the distance of the turntable.
    '''
    pass



def getHeight():
    '''
    Returns the height of the turntable.
    '''
    pass



def getLoop():
    '''
    Returns the state of the turntable animation loop mode.
    '''
    pass



def getPlaying():
    '''
    Returns the playback state of the turntable animation.
    '''
    pass



def setAngle(angle):
    '''
    Sets the angle of the turntable.
    '''
    pass



def setAnimationDuration(seconds):
    '''
    Sets the duration of the turntable animation.
    '''
    pass



def setDirection(direction):
    '''
    Sets the playback direction of the turntable animation.
    '''
    pass



def setDistance(distance):
    '''
    Sets the distance of the turntable.
    '''
    pass



def setHeight(height):
    '''
    Sets the height of the turntable.
    '''
    pass



def setLoop(enable):
    '''
    Sets the turntable animation to loop mode.
    '''
    pass



def setPlaying(value):
    '''
    Starts / stops the turntable animation.
    '''
    pass



def updateFromView():
    '''
    Update the turntable parameters from the current view.
    '''
    pass


