'''
Autogenerated Method-Stub for:
module vrdVirtualTouchpadButton
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getEndAngle():
    '''
    Gets the end angle of the virtual button.
    '''
    pass



def getMaxRadius():
    '''
    Gets the maximum radius of the virtual button.
    '''
    pass



def getMinRadius():
    '''
    Gets the minimum radius of the virtual button.
    '''
    pass



def getName():
    '''
    Gets the name of the virtual button.
    '''
    pass



def getStartAngle():
    '''
    Gets the start angle of the virtual button.
    '''
    pass



def getVirtualButtonId():
    '''
    Gets the virtual button id, which is set internally.
    '''
    pass



def setEndAngle(end):
    '''
    Sets the end angle of the virtual button.
    '''
    pass



def setMaxRadius(max):
    '''
    Sets the maximum radius if the virtual button.
    '''
    pass



def setMinRadius(min):
    '''
    Sets the minimum radius of the virtual button.
    '''
    pass



def setName(name):
    '''
    Sets the name of the virtual button.
    '''
    pass



def setStartAngle(start):
    '''
    Sets the start angle of the virtual button.
    '''
    pass



def vrdVirtualTouchpadButton():
    '''
    Default constructor.
    '''
    pass



def vrdVirtualTouchpadButton(button):
    '''
    Copy constructor.
    '''
    pass



def vrdVirtualTouchpadButton(name, minRadius, maxRadius, startAngle, endAngle):
    '''
    Constructor that creates an object with all necessary parameters to describe the virtual button.
    '''
    pass


