
# Autogenerated method stubs for 'vrGeometryEditor.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def tessellateSurfaces(nodes, chordalDeviation, normalTolerance, maxCoordLength, enableStitching, stitchingTolerance):
    '''
    Retessellates the given surfaces.

@param nodes: The list of nodes.

@type nodes: list of vrNodePtrs

@param chordalDeviation: The chordal deviation limit.

@type chordalDeviation: float

@param normalTolerance: The normal tolerance.

@type normalTolerance: float

@param maxCoordLength: The maximum length of a chord.

@type maxCoordLength: float

@param enableStitching: Sets stitching to either on or off.

@type status: boolean

@param stitchingTolerance: The maximum radius to use for stitching.

@type stitchingTolerance: float
    '''
    pass


