'''
Autogenerated Method-Stub for:
module vrHMDService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getEyeGaze():
    '''
    Returns tracked eye gaze data while eye tracking is active. Without eye tracking returns the forward looking ray of the HMD user. The gaze ray is in world coordinates.
    '''
    pass



def getEyeTrackingEnabled():
    '''
    Returns whether eye tracking should be enabled in VR. Please note this does not tell whether the HMD actually supports eye tracking or whether eye tracking is currently running. For the latter, use         vrHMDService.isEyeTrackingActive().
    '''
    pass



def getFovealRegionSize():
    '''
    Gets the size of the foveal region in foveated rendering mode.
    '''
    pass



def getFoveatedRenderingEnabled():
    '''
    Returns whether foveated rendering should be enabled in VR. Please note this does not tell whether the graphics card actually supports foveated rendering.
    '''
    pass



def getFoveatedRenderingQuality(preset):
    '''
    Gets the quality settings for a given preset.
    '''
    pass



def getFoveatedRenderingQualityPreset():
    '''
    Gets the quality preset that is used for foveated rendering. Get the individual settings for the preset with getFoveatedRenderingQuality(vrRenderTypes::FoveatedQualityPreset).
    '''
    pass



def getStarVRRenderSettings():
    '''
    Get current render settings that are specific for the StarVR HMD.
    '''
    pass



def isEyeTrackingActive():
    '''
    Returns whether eye tracking is currently active. It can only be active if enabled, while in VR and if the HMD has an eye tracker supported by VRED.
    '''
    pass



def isHmdActive():
    '''
    Check if an HMD (VR) display mode is active.
    '''
    pass



def setEyeTrackingEnabled(enabled):
    '''
    Enables or disables eye tracking in VR if supported by the connected HMD. If the option is set before VR mode is enabled, it is applied when entering VR. Enable eye tracking for foveated rendering.
    '''
    pass



def setFovealRegionSize(size):
    '''
    Sets the size of the foveal region in foveated rendering mode. See         vrHMDService.setFoveatedRenderingEnabled(enabled).
    '''
    pass



def setFoveatedRenderingCustomQuality(quality):
    '''
    Allows to set a custom configuration for the shading qualities used in foveated rendering mode. Enable the custom quality by setting         vrHMDService.setFoveatedRenderingQualityPreset(preset) to Custom.
    '''
    pass



def setFoveatedRenderingEnabled(enabled):
    '''
    Enables or disables foveated rendering in VR. This requires the OpenGL Shading Rate Image extension which is supported by NVIDIA Turing graphics cards. If the option is set before VR mode is enabled, it is applied when entering VR.
    '''
    pass



def setFoveatedRenderingQualityPreset(preset):
    '''
    Set the quality preset used for foveated rendering.
    '''
    pass



def setStarVRRenderSettings(settings):
    '''
    Apply specific render settings for the StarVR HMD. Changes to these settings take effect on next activation of StarVR HMD mode.
    '''
    pass


