'''
vrImmersiveUiService
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Interface to work with interactive VR windows and tools.
'''

from typing import List


class vrdImmersiveMenu():
    pass


class vrdImmersiveTool():
    pass


class QWidget():
    pass


def createMenu(name: str) -> vrdImmersiveMenu:
    '''
    Creates a new VR menu.
    '''
    return None


def createTool(name: str) -> vrdImmersiveTool:
    '''
    Creates a new VR tool visible on the VR tools menu.
    '''
    return None


def deleteMenu(menu: vrdImmersiveMenu):
    '''
    Removes a VR menu.
    '''
    pass


def deleteMenu(name: str):
    '''
    Removes a VR menu by name.
    '''
    pass


def deleteTool(tool: vrdImmersiveTool):
    '''
    Removes a VR tool.
    '''
    pass


def deleteTool(name: str):
    '''
    Remove a VR tool by name.
    '''
    pass


def findMenu(name: str) -> vrdImmersiveMenu:
    '''
    Find a VR menu by name.
    '''
    return None


def findTool(name: str) -> vrdImmersiveTool:
    '''
    Find a VR tool by name.
    '''
    return None


def getHideParticipantsVRPanel() -> bool:
    '''
    Get participants hide option.
    '''
    return None


def getHideStatusVRPanel() -> bool:
    '''
    Get status panel hide option.
    '''
    return None


def getTools():
    '''
    Documentation missing
    '''
    pass


def openToolsSubMenu(content: str):
    '''
    Opens a new tools sub menu with the given html content.
    '''
    pass


def openToolsSubMenu(widget: QWidget):
    '''
    Opens a new tools sub menu with the given widget.
    '''
    pass


def openToolsSubMenu(tool: vrdImmersiveTool):
    '''
    Opens the tools sub menu of the given         vrdImmersiveTool.
    '''
    pass


def setHideParticipantsVRPanel(value: bool):
    '''
    Hides the participants panel in the vr menu.
    '''
    pass


def setHideStatusVRPanel(value: bool):
    '''
    Hides the status panel with the current time in the vr menu.
    '''
    pass


def showToolsMenu(show: bool, rightHand: bool):
    '''
    Opens or closes the VR tools menu.
    '''
    pass


def toggleToolsMenu(rightHand: bool) -> bool:
    '''
    Toggles show/hide VR tools menu.
    '''
    return None


def toolChecked(tool: vrdImmersiveTool):
    '''
    Signal emitted, if a tool button is switched on.
    '''
    pass


def toolClicked(tool: vrdImmersiveTool):
    '''
    Signal emitted, if a tool button is clicked.
    '''
    pass


def toolSubMenuClosed(tool: vrdImmersiveTool):
    '''
    Signal emitted, if a tool sub menu is closed.
    '''
    pass


def toolSubMenuOpened(tool: vrdImmersiveTool):
    '''
    Signal emitted, if a tool sub menu is opened.
    '''
    pass


def toolUnchecked(tool: vrdImmersiveTool):
    '''
    Signal emitted, if a tool button is switched off.
    '''
    pass

