'''
Autogenerated Method-Stub for:
module vrImageService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createImage():
    '''
    Creates an empty image.
    '''
    pass



def loadImage(filename):
    '''
    Loads an image.
    '''
    pass



def readImageInformation(filename):
    '''
    Reads an image information.
    '''
    pass



def saveImage(image, filename):
    '''
    Saves an image.
    '''
    pass



def saveImageSequence(image, directory):
    '''
    Saves an image sequence.
    '''
    pass


