'''
vrImageService
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
Service for     vrdImage related functions.
'''

from typing import List


class vrdImage():
    pass


def createImage() -> vrdImage:
    '''
    Creates an empty image.
    '''
    return None


def loadImage(filename: str) -> vrdImage:
    '''
    Loads an image.
    '''
    return None


def readImageInformation(filename: str) -> str:
    '''
    Reads an image information.
    '''
    return None


def saveImage(image: vrdImage, filename: str) -> bool:
    '''
    Saves an image.
    '''
    return None


def saveImageSequence(image: vrdImage, directory: str) -> bool:
    '''
    Saves an image sequence.
    '''
    return None

