
# Autogenerated method stubs for 'vrInteraction.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def setNodeInteractableInVR(node, state):
    '''
    Enable / disable interaction with a scene node in VR.

When using the hand interaction in VR mode, Web Engines will receive events and Touch sensors will be triggered when the hand collides with the convex hull of the geometry. The geometry must have a volume (no flat/planar geometry). The node itself and its parent nodes may be translated and rotated, any child geometry may not be transformed.

Interactable nodes must not have a parent-child relationship in the scene tree.

@param node: The scene node.

@type node: vrNodePtr

@param state: Enable or disable interaction

@type state: bool
    '''
    pass


