
# Autogenerated method stubs for 'vrInteractionModule.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def setObjectDraggingIgnore(state):
    '''
    Enable/disable object dragging ignore mode.

@param state: Ignore dragging: On/Off.

@type state: bool
    '''
    pass


