'''
Autogenerated Method-Stub for:
module vrMathService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getRotation():
    '''
    Documentation missing
    '''
    pass



def getScaleFactor():
    '''
    Documentation missing
    '''
    pass



def getScaleOrientation():
    '''
    Documentation missing
    '''
    pass



def getTranslation():
    '''
    Documentation missing
    '''
    pass


