
# Autogenerated method stubs for 'vrMenu.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def vrMenu_update(name):
    '''
    Updates the menu with the name provided.

@param name: The name of the menu.

@type name: string
    '''
    pass


