'''
vrMeasurement
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def createCircleMeasurement(node1, node3, hitPoint3, hitPoint1, hitPoint2, node2):
    '''
    Creates a circle measurement.
    '''
    pass


def createGapMeasurement(node1, node2, hitPoint2, hitPoint1):
    '''
    Creates a gap measurement.
    '''
    pass


def createLineObjectMeasurement(lineNode, node2, linehitPoint):
    '''
    Creates a line to object measurement.
    '''
    pass


def createObjectObjectMeasurement(node1, node2):
    '''
    Creates an object to object measurement.
    '''
    pass


def createPointObjectMeasurement(node1, node2, hitPoint1):
    '''
    Creates a point to object measurement.
    '''
    pass


def createPointPointMeasurement(node1, node2, hitPoint2, hitPoint1):
    '''
    Creates a point to point measurement.
    '''
    pass


def removeAllMeasurements():
    '''
    Removes all existing measurements.
    '''
    pass


def removeSelectedMeasurement():
    '''
    Remove the currently selected measurement.
    '''
    pass


def updateAllMeasurements():
    '''
    Update all measurements.
    '''
    pass


def updateMeasurement():
    '''
    Update the selected measurement.
    '''
    pass


def zoomOnMeasurement():
    '''
    Zoom on the selected measurement.
    '''
    pass

