'''
vrMovieExport
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def createMovie(alpha, width, alphaRed, alphaGreen, alphaBlue, overwrite, ssf, stopFrame, height, alpha_premultiply, tonemap_hdr, filename, step, movie, startFrame, fps):
    '''
    Method to create a movie.
    '''
    pass


def createSnapshot(alpha, width, alphaRed, alphaGreen, alphaBlue, dpi, ssf, overwrite, height, alpha_premultiply, tonemap_hdr, filename, showImage):
    '''
    Method to create a snapshot.
    '''
    pass


def createSnapshotFast(filename):
    '''
    Create a fast snapshot with the provided file name.
    '''
    pass


def createSnapshotFastInit(height, width, ssf):
    '''
    Initializes the fast snapshot method setting the image resolution to width times height.
    '''
    pass


def createSnapshotFastTerminate():
    '''
    Terminates the creation of a fast snapshot.
    '''
    pass


def createSnapshotStream():
    '''
    
    '''
    pass


def getExportExrHalf():
    '''
    Return if EXR is exported in 16 bit float format.
    '''
    pass


def getExportMultiLayer():
    '''
    Return if TIFF/PSD is exported as layers for render passes.
    '''
    pass


def getExportTiffHDR():
    '''
    Return if TIFF/PSD is exported in HDR format.
    '''
    pass


def getLastRenderTime():
    '''
    Returns the duration in seconds of the last image render.
    '''
    pass


def imageStream():
    '''
    Redirects image write operations of function into a string which is returned.
    '''
    pass


def imageStreamBase64():
    '''
    Redirects image write operations of function into a string which is returned
    '''
    pass


def renderAnimation(alpha, width, alphaRed, alphaGreen, alphaBlue, overwrite, ssf, stopFrame, height, alpha_premultiply, tonemap_hdr, animation, filename, startFrame, fps):
    '''
    This method writes an animation as a movie in the specified resolution and supersampling and alpha channel.
    '''
    pass


def renderStepAnimation(alpha, width, alphaRed, alphaGreen, alphaBlue, overwrite, ssf, stopFrame, height, alpha_premultiply, animation, filename, step, startFrame, fps):
    '''
    This method writes an animation as a movie in the specified resolution and supersampling and alpha channel.
    '''
    pass


def resetActiveSnapshotMovieRenderPasses():
    '''
    Resets the active renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setActiveSnapshotMovieRenderPasses(diffuse_indirect_pass, incandescence_pass, diffuse_light_pass, material_id_pass, specular_light_pass, glossy_ibl_pass, glossy_light_pass, glossy_indirect_pass, diffuse_ibl_pass, occlusion_pass, normal_pass, depth_pass, beauty_pass, specular_reflection_pass, translucency_pass):
    '''
    Sets the active renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setAuxiliaryChannelsRenderPasses(crypto_object_pass, view_vector_pass, material_id_pass, mask_pass, occlusion_pass, position_pass, normal_pass, depth_pass):
    '''
    Sets the active combined channels renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setCombinedChannelsRenderPasses(diffuse_indirect_pass, incandescence_pass, diffuse_light_pass, glossy_ibl_pass, glossy_light_pass, glossy_indirect_pass, diffuse_ibl_pass, background_pass, transparency_pass, beauty_pass, specular_reflection_pass, translucency_pass):
    '''
    Sets the active combined channels renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setExportExrHalf(on):
    '''
    Enables/Disables export of EXR format in 16 bit float.
    '''
    pass


def setExportMultiLayer(on):
    '''
    Enables/Disables export of TIFF/PSD as layers for render passes.
    '''
    pass


def setExportTiffHDR(on):
    '''
    Enables/Disables export of TIFF/PSD in HDR format.
    '''
    pass


def setIlluminationChannelsRenderPasses(diffuse_indirect_pass, specular_indirect_pass, diffuse_light_pass, glossy_ibl_pass, glossy_light_pass, glossy_indirect_pass, diffuse_ibl_pass, translucency_indirect_pass, translucency_light_pass, translucency_ibl_pass):
    '''
    Sets the active illumination channels renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setImageProcessingRenderPasses(lens_flare_pass, backplate_pass, frontplate_pass, fog_pass):
    '''
    Sets the active image processing renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setMaterialChannelsRenderPasses(translucency_material_pass, glossy_material_pass, specular_material_pass, transparency_material_pass, diffuse_material_pass):
    '''
    Sets the active material channels renderpasses for rendering a snapshot using the createSnapshot or renderAnimation commands.
    '''
    pass


def setSnapshotEmbedMetaData(embedSwitchMaterialStates, embedSwitchNodeStates, embedCameraSettings, embedNodeVisibilities, embedRenderSettings):
    '''
    Sets which meta data to store within the output image.
    '''
    pass


def setSnapshotICCProfile(profileID):
    '''
    Sets the ICC Profile to store with the output image.
    '''
    pass


def setSnapshotNoShowImage(state):
    '''
    If state is set to true the rendered image is shown.
    '''
    pass


def setSnapshotQuality(quality):
    '''
    Sets the quality of the image to be exported.
    '''
    pass

