'''
vrNodeService
------------------------------------------
API version: v2 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------
A service that provides helper functions for working with vrdNodes.
'''

from typing import List


class string():
    pass


class integer():
    pass


class vrdNode():
    pass


class UnshareOption():
    pass


def clearFindCache():
    '''
    Clears the find cache.
    '''
    pass


def cloneNodes(nodes: List[vrdNode]) -> List[vrdNode]:
    '''
    Clone a list of nodes from the scene graph.
    '''
    return None


def findNode(name: string, wildcard: bool, includeComponents: bool, root: vrdNode) -> vrdNode:
    '''
    Finds the node via name.
    '''
    return None


def findNodes(name: string, wildcard: bool, includeComponents: bool, root: vrdNode) -> List[vrdNode]:
    '''
    Finds a list of nodes depending on their name.
    '''
    return None


def findNodesWithPath(path: string, wildcard: bool, root: vrdNode) -> List[vrdNode]:
    '''
    Finds a list of nodes depending on the node path.
    '''
    return None


def findNodeWithPath(path: string, wildcard: bool, root: vrdNode) -> vrdNode:
    '''
    Finds a node depending on its node path.
    '''
    return None


def getNodeFromId(nodeId: integer) -> vrdNode:
    '''
    Gets a node by its identifier.
    '''
    return None


def initFindCache():
    '''
    Build up an internal cache structure to speed up execution of find commands.
    '''
    pass


def removeNodes(nodes: List[vrdNode]):
    '''
    Removes a list of nodes from the scene graph.
    '''
    pass


def unshareNodes(nodes: List[vrdNode], option: UnshareOption):
    '''
    Unshare a list of nodes from the scene graph. Unshare will break the connection between two nodes which share the same settings.
    '''
    pass


def nodesAdded(nodes: List[vrdNode]):
    '''
    This signal will be send when new nodes was added.
    '''
    pass


def nodesRemoved(nodes: List[vrdNode]):
    '''
    This signal will be send when nodes was deleted.
    '''
    pass

