
# Autogenerated method stubs for 'vrNodePtr.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def createLight(type):
    '''
    Creates a light node with the given light type and adds it to the root node of the scenegraph.

Supported types are: UDirectionalLight, USpotLight, UPointLight, UDiskLight, URectangularLight, USphericalLight, URayLight.

@param type: The type of the light.

@type type: string
    '''
    pass



def toNode(id):
    '''
    Returns a node with the node id provided.

@param id: The node id.

@type id: unsigned int (32bit)

@return: The node.

@rtype: vrNodePtr
    '''
    pass


