
# Autogenerated method stubs for 'vrOpenVR.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getOpenVRFrameTimings():
    '''
    Windows only: Retrieves the frame timings. 

@return: see vrOpenVRFrameTimings documentation for more details.

@rtype: vrOpenVRFrameTimings
    '''
    pass



def getOpenVRTrackingOrigin():
    '''
    Returns the OpenVR tracking reference origin. Default is (0, 0, 0). Can be changed with setOpenVRTrackingOrigin.

@return: the OpenVR tracking reference origin .

@rtype: Pnt3f
    '''
    pass



def getOpenVRTrackingOriginType():
    '''
    Windows only: Retrieves the tracking origin type for OpenVR. 

@return: 0 = Seated, 1 = Standing (Room Scale).

@rtype: int
    '''
    pass



def resetOpenVRHMDPose():
    '''
    Resets the Seated Zero Pose for Seated tracking mode while OpenVR is running.

Execute this command while wearing the HMD and sitting in a comfortable position.
    '''
    pass



def setOpenVRControllerTracking(s):
    '''
    Windows only: Enables/Disables tracking of openvr controller. 

@param s: On/Off.

@type s: bool
    '''
    pass



def setOpenVRHMDForceInterleavedReprojection(s):
    '''
    Windows only: Enables/Disables forcing of interleaved reprojection. If enabled, the scene will be rendered with half the frame rate and every other frame will be interpolated.

@param s: On/Off.

@type s: bool
    '''
    pass



def setOpenVRHMDMirrorTextureView(eyeMode):
    '''
    Windows only: Sets the view to show in the VRED UI while using an OpenVR HMD.

@param eyeMode: Left Eye = 0, Right Eye = 1, Both Eyes = 2. The default is 0.

@type eyeMode: int
    '''
    pass



def setOpenVRHMDTracking(s):
    '''
    Windows only: Enables/Disables tracking of openvr hmd. 

@param s: On/Off.

@type s: bool
    '''
    pass



def setOpenVRHMDUseHiddenAreaMesh(s):
    '''
    Windows only: Enables/Disables the use of a hidden area mesh to mask out invisible areas in order to reduce shading costs.

@param s: On/Off.

@type s: bool
    '''
    pass



def setOpenVRTracking(s):
    '''
    Windows only: Enables/Disables tracking of openvr hmd and controller. 

@param s: On/Off.

@type s: bool
    '''
    pass



def setOpenVRTrackingOrigin(position):
    '''
    Sets the tracking reference origin for OpenVR tracking. Use it to correct any offsets in the scene. 
This function always assumes Y-Up, even if Z-up is set in the scene.

If the tracking origin should be at pos = (x_scene, y_scene, z_scene) in the VRED scene, call setOpenVRTrackingOrigin(Pnt3f(-x_scene, -z_scene, y_scene)).

@param position: Position offset for the OpenVR tracking.

@type position: Pnt3f
    '''
    pass



def setOpenVRTrackingOriginType(originType):
    '''
    Windows only: Sets the tracking origin type for OpenVR. 

@param originType: 0 = Seated, 1 = Standing.

@type originType: int
    '''
    pass


