'''
vrOpenPDM
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def pdmBar():
    '''
    Bar
    '''
    pass


def pdmExport(name, type, revision):
    '''
    Export object form PDM system
    '''
    pass


def pdmFoo(name, type, revision):
    '''
    Foo
    '''
    pass


def pdmLoadTest():
    '''
    loadTest
    '''
    pass


def pdmLogin(system, user, password):
    '''
    Login to PDM system
    '''
    pass


def pdmPullTest():
    '''
    pullTest
    '''
    pass

