
# Autogenerated method stubs for 'vrQObject.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def findQObject(root, name):
    '''
    Searches for a QObject via name. Two sets of parameters are valid:

findQObject(name) or

findQObject(root,name).

@param root: The root QObject.

@type root: vrQObject

@param name: The name of the Object.

@type name: string

@return: The retrieved QObject.

@rtype: vrQObject
    '''
    pass


