'''
Autogenerated Method-Stub for:
module vrReferenceService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def convertToSmart(node, useSourcePath):
    '''
    Converts the passed node into a smart reference.
    '''
    pass



def createSmart(parent):
    '''
    Creates a new smart reference below the given parent.
    '''
    pass



def createSource(path, parent):
    '''
    Creates a new source reference with the given path.
    '''
    pass



def getAllAvailableFileFormats():
    '''
    Returns a list with all file endings used in the loaded references (source and smart).
    '''
    pass



def getChildReferences():
    '''
    Documentation missing
    '''
    pass



def getCustomExportPath():
    '''
    Queries the custom export path.
    '''
    pass



def getExportLocation():
    '''
    Queries the default smart export location mode.
    '''
    pass



def getLoadMode():
    '''
    Queries the load mode for smart references.
    '''
    pass



def getNotificationMode():
    '''
    Queries the current file change notification mode.
    '''
    pass



def getParentReferences():
    '''
    Documentation missing
    '''
    pass



def getReferences():
    '''
    Documentation missing
    '''
    pass



def getRevisionMonitoringEnabled():
    '''
    Documentation missing
    '''
    pass



def getRevisionMonitoringExpressions():
    '''
    Documentation missing
    '''
    pass



def getSceneReferences():
    '''
    Get all references in the scene
    '''
    pass



def getShowConvertToSmartWarning():
    '''
    Queries the convert to smart warning flag.
    '''
    pass



def getUpdateMonitoringEnabled():
    '''
    Checks if update monitoring is currently enabled.
    '''
    pass



def getUpdateMonitoringInterval():
    '''
    Returns the current time between background update checks in miliseconds.
    '''
    pass



def getUpdateMonitoringPaused():
    '''
    Queries if the background update monitoring is currently in pause mode.
    '''
    pass



def pauseUpdateMonitoring(state):
    '''
    Temporarily pauses / unpauses the background update monitoring. This will suspend the asynchrounous update check but will not cancel it.
    '''
    pass



def reimportSmartReferences(references):
    '''
    Reimports the list of given smart references.
    '''
    pass



def reimportSourceReferences():
    '''
    Documentation missing
    '''
    pass



def removeReference(node):
    '''
    Converts the passed node into a none reference node.
    '''
    pass



def setCustomExportPath(path):
    '''
    Sets the custom path for exported smart references. This path will be used, when the location is set to Custom.
    '''
    pass



def setExportLocation(value):
    '''
    Changes the default location mode for unsaved smart references.
    '''
    pass



def setLoadMode(value):
    '''
    Sets the load mode for smart references. LoadedReferences -> preserve the load state saved in the project AllReferences -> load all smart references NoReferences -> Do not load any smart reference LoadedSkipLeafReferences -> Load all but the leafes of the reference tree.
    '''
    pass



def setNotificationMode(value):
    '''
    Sets the file change notification monitoring mode.
    '''
    pass



def setRevisionMonitoringEnabled(value):
    '''
    Enables revision number check for update monitoring.
    '''
    pass



def setRevisionMonitoringExpressions(expressions):
    '''
    Sets the list of regular expressions used to detect revision numbers.
    '''
    pass



def setShowConvertToSmartWarning(value):
    '''
    Enables or disables warnings on convert to smart.
    '''
    pass



def setUpdateMonitoringEnabled(value):
    '''
    Starts / stops the background update monitoring.
    '''
    pass



def setUpdateMonitoringInterval(msecs):
    '''
    Sets the update monitoring interval in miliseconds.
    '''
    pass



def sortRevisions(revisions):
    '''
    Sorts a list of revisions from oldest to newest.
    '''
    pass


