'''
vrRenderLayerModule
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def activateRenderLayer(name):
    '''
    Activates a renderlayer.
    '''
    pass


def activateRenderLayerState(name):
    '''
    Activates stored node visibility states for the whole scene.
    '''
    pass


def addNodesToRenderLayer(layerName, nodes):
    '''
    Add nodes to a renderlayer.
    '''
    pass


def createRenderLayer(name):
    '''
    Activates a renderlayer.
    '''
    pass


def resetNodeVisibilityFlags(node):
    '''
    Resets the node visibility flags for a given node and its children.
    '''
    pass


def resetRenderLayers():
    '''
    Resets all activated render layers.
    '''
    pass


def setNodeVisibilityFlags(node, receiveShadows, castShadowOnShadowMaterial, visibleForPhotons, primaryVisibility, visibleInAlpha, visibleInReflections, doubleSided, visible, castShadows, useOverrideMaterial, visibleInRefractions, overrideMaterial):
    '''
    Sets the visibility flags and the override material for a given node and its children.
    '''
    pass

