'''
vrRoute
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def createRoute(fromNodename, toNodename, toFieldname, fromFieldname):
    '''
    Creates a route between two nodes: "from" and "to".
    '''
    pass

