'''
Autogenerated Method-Stub for:
module vrRoute
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def createRoute(fromFieldname, fromNodename, toFieldname, toNodename):
    '''
    Creates a route between two nodes: "from" and "to".
    '''
    pass


