
# Autogenerated method stubs for 'vrRoute.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def createRoute(fromNodename, fromFieldname, toNodename, toFieldname):
    '''
    Creates a route between two nodes: "from" and "to".

@param fromNodename: The name of the node "from".

@type fromNodename: string

@param fromFieldname: The name of the field "from".

@type fromFieldname: string

@param toNodename: The name of the node "to".

@type toNodename: string

@param toFieldname: The name of the field "to".

@type toFieldname: string
    '''
    pass


