'''
vrRuler
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def getRulerEnabled():
    '''
    Returns whether the ruler is enabled.
    '''
    pass


def getRulerFixAxes():
    '''
    Returns whether the ruler scale markings and the grid should adapt to the camera distance.
    '''
    pass


def getRulerGridEnabled():
    '''
    Returns whether the grid is shown.
    '''
    pass


def getRulerManipulatorEnabled():
    '''
    Returns whether the manipulator is shown.
    '''
    pass


def getRulerPosition():
    '''
    Returns the current position of the ruler.
    '''
    pass


def getRulerRotation():
    '''
    Returns the current rotation of the ruler as Euler angles.
    '''
    pass


def resetRuler():
    '''
    Resets the position and rotation of the ruler.
    '''
    pass


def setRulerFixAxes(state):
    '''
    Sets whether the ruler scale markings and the grid should adapt to the camera distance.
    '''
    pass


def setRulerPosition(y, z, x):
    '''
    Sets the position of the ruler.
    '''
    pass


def setRulerRotation(rotationZ, rotationY, rotationX):
    '''
    Sets the rotation of the ruler with Euler rotation angles.
    '''
    pass


def showRuler(state):
    '''
    Shows or hides the Ruler.
    '''
    pass


def showRulerGrid(state):
    '''
    Shows/hides the ruler grid.
    '''
    pass


def showRulerManipulator(state):
    '''
    Shows/hides the ruler manipulator.
    '''
    pass

