'''
vrScript
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def cameraViewRedo():
    '''
    Redo the last view change.
    '''
    pass


def cameraViewUndo():
    '''
    Undo the last view change.
    '''
    pass


def clearScript():
    '''
    Clear python script in the script editor.
    '''
    pass


def executePython(command):
    '''
    Execute a python command.
    '''
    pass


def executePythonR(command):
    '''
    Execute a python command and return the return value as a string.
    '''
    pass


def redo():
    '''
    Redo the last command.
    '''
    pass


def secureImport():
    '''
    
    '''
    pass


def undo():
    '''
    Undo the last command.
    '''
    pass

