'''
Autogenerated Method-Stub for:
module vrScenegraph
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def addNodeTag(node, tag):
    '''
    Adds a tag to the node.
    '''
    pass



def addNodeTag(tag, nodes):
    '''
    Adds a tag to the node.
    '''
    pass



def addNodeTag(node, tags):
    '''
    Adds a list of tags to the node.
    '''
    pass



def addNodeTag(tags, nodes):
    '''
    Adds a list of tags to a list of node.
    '''
    pass



def getNodesWithTag(tag):
    '''
    Returns a list of nodes which have the metadatatag assigned starting from the root node.
    '''
    pass



def getNodesWithTag(node, tag):
    '''
    Returns a list of nodes which have the metadatatag assigned starting from the root node.
    '''
    pass



def getNodesWithTags(tags, matchAllTags):
    '''
    Returns a list of nodes which have the metadatatag assigned.
    '''
    pass



def getNodesWithTags(node, tags, matchAllTags):
    '''
    Returns a list of nodes which have the metadatatag assigned.
    '''
    pass



def removeNodeTag(node, tag):
    '''
    Removes a tag from a node.
    '''
    pass



def removeNodeTag(tag, nodes):
    '''
    Removes a tag from the given nodes.
    '''
    pass



def removeNodeTags(node, tags):
    '''
    Removes the tags from a node.
    '''
    pass



def removeNodeTags(tags, nodes):
    '''
    Removes the tags from the given nodes.
    '''
    pass



def replaceNodeTag(node, oldTag, newTag):
    '''
    Replaces an existing tag.
    '''
    pass



def replaceNodeTag(newTag, oldTag, nodes):
    '''
    Replaces an existing tag.
    '''
    pass



def setIgnoreMaterialGroup(ignore, nodepath):
    '''
    Ignores a material group.
    '''
    pass



def setIgnoreMaterialGroup(node, ignore):
    '''
    Ignores a material group.
    '''
    pass



def addChilds(node, children):
    '''
    Adds a list of child nodes to a node.
    '''
    pass



def addNodeTags():
    '''
    Documentation missing
    '''
    pass



def applyMaterial(mats, skipMaterialGroupChilds, nodes, applyToMaterialGroupParent):
    '''
    Applies a list of materials to a list of nodes.
    '''
    pass



def clearFindCache():
    '''
    Clears the find cache.
    '''
    pass



def cloneMirrorAxisNode(flush, node, axis, deep):
    '''
    Clone mirrors a subtree at a specific axis.
    '''
    pass



def cloneMirrorNode(flush, node, deep):
    '''
    Clone mirrors a subtree at the y-axis.
    '''
    pass



def cloneNode(node, deep):
    '''
    Clones a subtree.
    '''
    pass



def convertCore(node, type):
    '''
    Converts the core of a node to another type.
    '''
    pass



def copyNode(node):
    '''
    Copy a node from the scenegraph.
    '''
    pass



def copyNodes(nodes):
    '''
    Copy a list of nodes from the scenegraph.
    '''
    pass



def copyTransformation(copyScalePivot, source, copyScale, copyTranslation, copyShearing, copyRotatePivot, copyRotation, target):
    '''
    Copies the transformation of one node to another.
    '''
    pass



def createNode(parent, name, type):
    '''
    Creates a new node of a given type ans name into the scenegraph as a child of given parent.
    '''
    pass



def cutNode(node):
    '''
    Cut a node from the scenegraph.
    '''
    pass



def cutNodes(nodes):
    '''
    Cut a list of nodes from the scenegraph.
    '''
    pass



def deleteNode(node, force):
    '''
    Deletes a node.
    '''
    pass



def deleteNodes(nodes, force):
    '''
    Deletes a list of nodes.
    '''
    pass



def deselectAll():
    '''
    Deselects all objects from scenegraph.
    '''
    pass



def enableScenegraph(status):
    '''
    Enables scenegraph updates.
    '''
    pass



def findNode(regex, node_name):
    '''
    Finds the node via name.
    '''
    pass



def findNodePath(regex, node_path):
    '''
    Finds the node via path name.
    '''
    pass



def findNodes(node_names, regex, node_name):
    '''
    Finds the node via name.
    '''
    pass



def findUniquePath(unique_path):
    '''
    Finds the node via path unique path
    '''
    pass



def getAllNodes():
    '''
    Returns a list of all scenegraph nodes.
    '''
    pass



def getClipboard():
    '''
    Returns a list of all nodes in the clipboard.
    '''
    pass



def getHeadlight():
    '''
    Returns the headlight node.
    '''
    pass



def getInternalRootNode():
    '''
    Returns the internal root node.
    '''
    pass



def getNodeID(name):
    '''
    Returns the node id of the node with the provided name.
    '''
    pass



def getNodeName(node):
    '''
    Returns the name of a node.
    '''
    pass



def getNodePath(node):
    '''
    Returns the whole path name of a node.
    '''
    pass



def getNodeTags(node):
    '''
    Returns the list of tags attached to the given node.
    '''
    pass



def getRootNode():
    '''
    Returns the root node.
    '''
    pass



def getSceneSwitches():
    '''
    Finds all the switches in the scene.
    '''
    pass



def getSelectedNode():
    '''
    Returns the selected node.
    '''
    pass



def getSelectedNodes():
    '''
    Returns a list of selected nodes.
    '''
    pass



def getSelectedRootNodes():
    '''
    Returns a list of selected root nodes.
    '''
    pass



def getSuperRootNode():
    '''
    Returns the super root node.
    '''
    pass



def getTransformRootNode():
    '''
    Returns the transform root node.
    '''
    pass



def getUniquePath(node):
    '''
    Returns a unique path for this node.
    '''
    pass



def groupSelection():
    '''
    Groups the selected nodes under a newly created Transform3D node.
    '''
    pass



def hasNodeTag(node, tag):
    '''
    Checks if a node has a certain tag.
    '''
    pass



def hasNodeTags(node, tag):
    '''
    Checks if a node has a certain tag.
    '''
    pass



def hideNode(node):
    '''
    Hide the node from the perspective view and disable it on the scenegraph.
    '''
    pass



def hideNodes(nodes):
    '''
    Hide the nodes in the list from the perspective view and disable them on the scenegraph.
    '''
    pass



def ignoreAutoHeadlight():
    '''
    Ignores the automatic headlight if another lightsource is set.
    '''
    pass



def initFindCache():
    '''
    Build up an internal cache structure to speed up execution of the python commands findNode and findNodes.
    '''
    pass



def insertParentNode(node, newParent):
    '''
    Insert a new parent node.
    '''
    pass



def invertSelection():
    '''
    Inverts the current selection in the scenegraph.
    '''
    pass



def invertSelectionInGroup():
    '''
    Inverts the current selection inside the parent group in the scenegraph.
    '''
    pass



def isCloned(node):
    '''
    Checks if a node is cloned.
    '''
    pass



def macget():
    '''
    Documentation missing
    '''
    pass



def moveNode(node, from_, to):
    '''
    Move a node from "from" to "to".
    '''
    pass



def moveNodes(froms, nodes, tos):
    '''
    Move a List of nodes from a list "from" to a list "to".
    '''
    pass



def moveNodesAfter():
    '''
    Internal function.
    '''
    pass



def pasteNode(node):
    '''
    Paste a node into the scenegraph.
    '''
    pass



def pasteNodes(nodes):
    '''
    Paste some nodes into the scenegraph.
    '''
    pass



def rebuildClones():
    '''
    Rebuilds all clone nodes in case a operation has broken the cloning.
    '''
    pass



def removeSelectedNodes(nodes):
    '''
    Removes the selected node
    '''
    pass



def selectAll():
    '''
    Selects all objects from the scenegraph.
    '''
    pass



def selectNode(node, status, name):
    '''
    Select/Deselect a node.
    '''
    pass



def selectNodes(status, nodes):
    '''
    Select/Deselects multiple nodes.
    '''
    pass



def selectNodesNoUndo(status, nodes):
    '''
    Select/Deselects multiple nodes.
    '''
    pass



def selectParent():
    '''
    Selects the parent node from the currently selected node in the scenegraph.
    '''
    pass



def setBoundingBoxSelection(enabled):
    '''
    Sets bounding box selection mode.
    '''
    pass



def setSwitchChoiceByTag(node, tags):
    '''
    Sets the choice of a switch node based on the given tag.
    '''
    pass



def setSwitchChoiceByTags(node, tags, matchAllTags):
    '''
    Sets the choice of a switch node based on the given tags.
    '''
    pass



def showComponents(enabled):
    '''
    Sets show components mode.
    '''
    pass



def showNode(node):
    '''
    Show the node in the perspective view and enable it on the scenegraph.
    '''
    pass



def showNodes(nodes):
    '''
    Show the nodes in the list from the perspective view and enable them on the scenegraph.
    '''
    pass



def showScenegraph(status):
    '''
    Shows/hides the scenegraph widget.
    '''
    pass



def splitGeometryTris():
    '''
    Splits a geometry into triangles.
    '''
    pass



def subChilds(node, children):
    '''
    Remove a list of children from a node.
    '''
    pass



def uncreateNode(node, parent, name, type):
    '''
    Uncreates node with node, type, name, and parent.
    '''
    pass



def undeleteNode(node):
    '''
    Undeletes a node.
    '''
    pass



def undeleteNodes(nodes):
    '''
    Undelete a list of nodes.
    '''
    pass



def unshareNode(node):
    '''
    Unshares a subtree.
    '''
    pass



def unsplitGeometryTris():
    '''
    Merges a geometry that was split into triangles back to one geometry.
    '''
    pass



def updateScenegraph(force):
    '''
    Updates scenegraph.
    '''
    pass


