'''
Autogenerated Method-Stub for:
module vrSceneplateService
------------------------------------------

API version: v2
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def clearSelection():
    '''
    Clears the current sceneplate selection.
    '''
    pass



def copyNodes(nodes):
    '''
    Copy Nodes.
    '''
    pass



def createGroupForNodes(nodes):
    '''
    All given nodes will be moved to a new created group.
    '''
    pass



def createNode(parent, type, name):
    '''
    Creates a new sceneplate node.
    '''
    pass



def createSwitchForNodes(nodes):
    '''
    All given nodes will be moved to a new created switch.
    '''
    pass



def cutNodes(nodes):
    '''
    Cut nodes.
    '''
    pass



def duplicateNodes(nodes):
    '''
    Duplicate the nodes.
    '''
    pass



def findNode(name):
    '''
    Returns the first node found in sceneplate hierarchy with the given name.
    '''
    pass



def findNodes(name):
    '''
    Returns list of nodes found in sceneplate hierarchy with the given name.
    '''
    pass



def getAllNodes():
    '''
    Returns all nodes (sceneplates, groups and switches)
    '''
    pass



def getAllSceneplates():
    '''
    Returns all sceneplates (excluding groups and switches)
    '''
    pass



def getDefaultBackgroundColor():
    '''
    Returns the default background color for new created (text) sceneplates.
    '''
    pass



def getDefaultBackgroundTransparency():
    '''
    Returns the default background transparency for new created (text) sceneplates.
    '''
    pass



def getDefaultFont():
    '''
    Returns the default font for new created (text) sceneplates.
    '''
    pass



def getDefaultFontColor():
    '''
    Returns the default font color for new created (text) sceneplates.
    '''
    pass



def getPreviewImage(sceneplate):
    '''
    Returns an image for a node, the image shows the current content of the sceneplate. If a group or switch is selected the content of the first visible sceneplate will be returned.
    '''
    pass



def getRootNode():
    '''
    Returns the root node of all sceneplates.
    '''
    pass



def getSelectedNodes():
    '''
    Returns the currently selected nodes.
    '''
    pass



def loadNodes(filename):
    '''
    Load sceneplate nodes from file with the given name.
    '''
    pass



def pasteAllAttributes(nodes):
    '''
    Paste all attributes from the first node in copy buffer to the given nodes.
    '''
    pass



def pasteColorCorrection(nodes):
    '''
    Paste color correction setting from the first node in copy buffer to the given nodes.
    '''
    pass



def pasteNodes(targetRoot):
    '''
    Paste nodes.
    '''
    pass



def pasteProperties(nodes):
    '''
    Paste properties (all information about the content) from the first node in copy buffer to the given nodes.
    '''
    pass



def pasteSizeAndPosition(nodes):
    '''
    Paste size and position from the first node in copy buffer to the given nodes.
    '''
    pass



def reloadWebPage(nodes):
    '''
    Reloads the web pages of the given nodes.
    '''
    pass



def removeAllGroups():
    '''
    Removes all groups (not switches) from the sceneplate hierarchy.
    '''
    pass



def removeNodes(nodes):
    '''
    Remove nodes from sceneplates.
    '''
    pass



def saveNodes(filename, nodes):
    '''
    Saves the nodes to the file with the given name.
    '''
    pass



def setDefaultBackgroundColor(color):
    '''
    Sets the default background color for new created (text) sceneplates.
    '''
    pass



def setDefaultBackgroundTransparency(transparency):
    '''
    Sets the default background transparency for new created (text) sceneplates.
    '''
    pass



def setDefaultFont(font):
    '''
    Sets the default font for new created (text) sceneplates.
    '''
    pass



def setDefaultFontColor(color):
    '''
    Sets the default font color for new created (text) sceneplates.
    '''
    pass



def setSelectedNodes(nodes):
    '''
    Sets the sceneplate selection.
    '''
    pass


