
# Autogenerated method stubs for 'vrScript.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def cameraViewRedo():
    '''
    Redo the last view change.
    '''
    pass



def cameraViewUndo():
    '''
    Undo the last view change.
    '''
    pass



def clearScript():
    '''
    Clear python script in the script editor.
    '''
    pass



def executePython(command):
    '''
    Execute a python command.

@param command: The command.

@type command: string

@return: True on success, false otherwise.

@rtype: bool
    '''
    pass



def executePythonR(command):
    '''
    Execute a python command and return the return value as a string.

@param command: The command.

@type command: string

@return: The return value.

@rtype: string
    '''
    pass



def redo():
    '''
    Redo the last command.
    '''
    pass



def undo():
    '''
    Undo the last command.
    '''
    pass


