'''
vrSequencer
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def getAllSequencesActionCount():
    '''
    Returns the number of active actions in all sequences.
    '''
    pass


def getSequenceList():
    '''
    Returns a list of sequences.
    '''
    pass


def readSequenceXML(file):
    '''
    Read sequences from XML file .
    '''
    pass


def runAllSequences():
    '''
    Runs all sequences.
    '''
    pass


def runSequence(name):
    '''
    Run sequence with a given name.
    '''
    pass


def runSequenceHttp(name, url, id):
    '''
    Run sequence with a given name.
    '''
    pass

