
# Autogenerated method stubs for 'vrSpeech.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def setVoiceType(id):
    '''
    Sets the voice type id

@param id: id of voice

@type: id: integer
    '''
    pass



def speak(text):
    '''
    Speaks a text 

@param text: Text to speak

@type: text: string
    '''
    pass


