'''
Autogenerated Method-Stub for:
module vrStarVR
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def getStarVREyeGaze():
    '''
    Returns the eye gaze origin and target in world coordinates.
    '''
    pass



def getStarVRFoveatedFovFactor():
    '''
    Returns the FOV factor used for foveated rendering.
    '''
    pass



def getStarVRFoveatedRendering():
    '''
    Returns whether foveated rendering is enabled for StarVR.
    '''
    pass



def getStarVRFoveatedResolutionScale():
    '''
    Returns the resolution scale factor for the foveated area (high-resolution).
    '''
    pass



def getStarVRFrontViewResolutionScale():
    '''
    Returns resolution scale for front viewports in non-foveated rendering.
    '''
    pass



def getStarVRNonFoveatedResolutionScale():
    '''
    Returns the resolution scale factor for the non-foveated area (low-resolution).
    '''
    pass



def getStarVRSideViewResolutionScale():
    '''
    Returns resolution scale for side viewports in non-foveated rendering.
    '''
    pass



def setStarVRFoveatedFovFactor(f):
    '''
    Set FOV factor for foveated rendering.
    '''
    pass



def setStarVRFoveatedRendering(s):
    '''
    Enables/Disables foveated rendering for StarVR HMD.
    '''
    pass



def setStarVRFoveatedResolutionScale(f):
    '''
    Set resolution scale for foveated area (high-resolution).
    '''
    pass



def setStarVRFrontViewResolutionScale(f):
    '''
    Set resolution scale for front viewports in non-foveated rendering.
    '''
    pass



def setStarVRNonFoveatedResolutionScale(s):
    '''
    Set resolution scale for non-foveated area (low-resolution).
    '''
    pass



def setStarVRSideViewResolutionScale(f):
    '''
    Set resolution scale for side viewports in non-foveated rendering.
    '''
    pass



def setStarVRSingleTexture(s):
    '''
    Render only one texture per eye in non-foveated rendering mode, instead of the two 'front' and 'side' view textures.
    '''
    pass


