'''
vrSurfaceAnalysis
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def enableSurfaceAnalysis(state):
    '''
    Enable/disable surface analysis render mode.
    '''
    pass


def setSurfaceAnalysisDirection(state):
    '''
    Sets light direction.
    '''
    pass


def setSurfaceAnalysisLineColor(state):
    '''
    Sets lines/stripes color.
    '''
    pass


def setSurfaceAnalysisLineCount(state):
    '''
    Sets lines/stripes count.
    '''
    pass


def setSurfaceAnalysisLineType(state):
    '''
    Sets lines/stripes mode.
    '''
    pass


def setSurfaceAnalysisMode(state):
    '''
    Sets surface analysis mode.
    '''
    pass


def setSurfaceAnalysisPickNormal(state):
    '''
    Enable/disable pick surface normal.
    '''
    pass


def setSurfaceAnalysisSetToXAxis():
    '''
    Sets light source direction to X axis.
    '''
    pass


def setSurfaceAnalysisSetToYAxis():
    '''
    Sets light source direction to Y axis.
    '''
    pass


def setSurfaceAnalysisSetToZAxis():
    '''
    Sets light source direction to Z axis.
    '''
    pass


def setSurfaceAnalysisShowDirection(state):
    '''
    Enable/disable show light direction.
    '''
    pass


def setSurfaceAnalysisSurfaceBaseColor(state):
    '''
    Sets surface color.
    '''
    pass


def setSurfaceAnalysisSurfaceLightingMode(state):
    '''
    Sets surface mode.
    '''
    pass


def setSurfaceAnalysisUseCamVec(state):
    '''
    Enable/disable use camera view vector.
    '''
    pass

