
# Autogenerated method stubs for 'vrTouchSensor.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def triggerTouchSensor(name):
    '''
    Triggers a touch sensor.

@param name: The name of the touch sensor.

@type name: string
    '''
    pass


