'''
vrTransform
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def selectTransformVariantByName(name, node):
    '''
    Applies a transform variant of a given node by name.
    '''
    pass


def selectTransformVariantByName(nodeName, variantName):
    '''
    Applies a transform variant for a given node by name.
    '''
    pass


def selectTransformVariantByIndex(node, index):
    '''
    Applies a transform variant of a given node by index.
    '''
    pass


def selectTransformVariantByIndex(nodeName, index):
    '''
    Applies a transform variant of a given node by index.
    '''
    pass


def captureTransformVariants(nodes, name):
    '''
    Creates transform variants with the given name for all nodes passed to this function.
    '''
    pass


def getBBCenter():
    '''
    Internal Function.
    '''
    pass


def pickAxis():
    '''
    Defines rotation axis over two pick points.
    '''
    pass


def pickAxis3Points():
    '''
    Defines rotation axis over three pick points.
    '''
    pass

