'''
vrTransform
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def selectTransformVariantByName(name, node):
    '''
    Applies a transform variant of a given node by name.
    '''
    pass


def selectTransformVariantByName(variantName, nodeName):
    '''
    Applies a transform variant for a given node by name.
    '''
    pass


def selectTransformVariantByIndex(index, node):
    '''
    Applies a transform variant of a given node by index.
    '''
    pass


def selectTransformVariantByIndex(index, nodeName):
    '''
    Applies a transform variant of a given node by index.
    '''
    pass


def captureTransformVariants(name, nodes):
    '''
    Creates transform variants with the given name for all nodes passed to this function.
    '''
    pass


def getBBCenter():
    '''
    Internal Function.
    '''
    pass


def pickAxis():
    '''
    Defines rotation axis over two pick points.
    '''
    pass


def pickAxis3Points():
    '''
    Defines rotation axis over three pick points.
    '''
    pass

