'''
Autogenerated Method-Stub for:
module vrTransformHelper
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def activateRotateManipulator():
    '''
    Activates the Rotate Helper.
    '''
    pass



def activateScaleManipulator():
    '''
    Activates the Scale Helper.
    '''
    pass



def activateTranslateManipulator():
    '''
    Activates the Translate Helper.
    '''
    pass



def activateUniversalManipulator():
    '''
    Activates the Universal Helper.
    '''
    pass



def showTransformManipulator(state):
    '''
    Displays the Transform Helper.
    '''
    pass



def togglePivotManipulator():
    '''
    Activates the Pivot Helper.
    '''
    pass


