'''
vrUVEditor
------------------------------------------
API version: v1 | Generation Date: 2020-09-13 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from __future__ import annotations
from typing import List


def getAutoMaxIterations():
    '''
    Returns whether automatic max iterations is enabled.
    '''
    pass


def setAutoMaxIterations():
    '''
    setAutoMaxIterations( (bool)enable) -> None : Enables/disables automatic max iterations for unfolding operation.
    '''
    pass

