
# Autogenerated method stubs for 'vrUVEditor.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getAutoMaxIterations():
    '''
    getAutoMaxIterations() -> bool :
    Returns whether automatic max iterations is enabled.
    
    @return: Whether automatic max iterations is enabled.
    
    @rtype: bool

    C++ signature :
        bool getAutoMaxIterations()
    '''
    pass



def setAutoMaxIterations(enable):
    '''
    setAutoMaxIterations( (bool)enable) -> None :
    Enables/disables automatic max iterations for unfolding operation. 
    
    @param enable: If true, automatic max iterations is enabled.
    
    @type name: bool

    C++ signature :
        void setAutoMaxIterations(bool)
    '''
    pass


