'''
Autogenerated Method-Stub for:
module vrVariants
------------------------------------------

API version: v1
Generation Date: 2020-04-24

VRED-Py: Visual Studio Code Tools for Autodesk VRED
'''

from typing import List



def selectVariantSet(name):
    '''
    Activates a variant set.
    '''
    pass



def selectVariantSet(name, excludeViewpoint):
    '''
    Activates a variant set.
    '''
    pass



def activateCapturedVariantSet(name):
    '''
    Activates a captured variant set.
    '''
    pass



def createAndCaptureVariantSet(name):
    '''
    Captures variants to variant set.
    '''
    pass


