
# Autogenerated method stubs for 'vrVRHero.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getVRHeroHMDIPD():
    '''
    Returns the HMD IPD distances for left and right eye in millimeter).

@return: HMD Ipd values for left and right eye

@rtype: Vec2f
    '''
    pass



def setVRHeroHMDIPD(rightDistanceToCenter):
    '''
    Sets the HMD IPD distances for left and right eye in millimeter. If both parameters are 0.0f the automatic IPD calculation will be triggered.@param leftDistanceToCenter: left eye distance to center in millimeter.

@type leftDistanceToCenter: float

@param rightDistanceToCenter: right eye distance to center in millimeter.

@type rightDistanceToCenter: float
    '''
    pass


