'''
vrVRHero
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def getVRHeroHMDIPD():
    '''
    Returns the HMD IPD distances for left and right eye in millimeter).
    '''
    pass


def setVRHeroHMDIPD(rightDistanceToCenter):
    '''
    Sets the HMD IPD distances for left and right eye in millimeter.
    '''
    pass

