'''
vrVRMLViewPoints
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def setVRMLCurrentViewpoint(name):
    '''
    Set the current viewpoint.
    '''
    pass


def setVRMLViewPointsEnabled(state):
    '''
    Enables VRML viewpoints.
    '''
    pass

