
# Autogenerated method stubs for 'vrVRMLViewPoints.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def setVRMLCurrentViewpoint(name):
    '''
    Set the current viewpoint.

@param name: The name of the viewpoint.

@type name: string
    '''
    pass



def setVRMLViewPointsEnabled(state):
    '''
    Enables VRML viewpoints.

@param state: Viewpoints: Enable/Disable.

@type state: bool
    '''
    pass


