
# Autogenerated method stubs for 'vrVrpnTrackingService.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def getFreezeTracking():
    '''
    Returns Freeze tracking state.

@return: True if the tracking is frozen, false otherwise.

@rtype: bool
    '''
    pass



def isTracking():
    '''
    Returns true if tracking is currently enabled.

@return: True if the tracking is enabled, false otherwise.

@rtype: bool
    '''
    pass



def loadTrackingConfig(file):
    '''
    Load tracking configuration from file.

@param file: Config file path.

@type file: string
    '''
    pass



def setBodyRelativeToNavigator(name, value):
    '''
    Sets body transformation relative to navigator.

@param name: Body name.

@type name: string

@param value: True if relative, False otherwise.

@type value: bool
    '''
    pass



def setFreezeTracking(state):
    '''
    Freeze tracking.

@param state: The state of the tracking: Freeze/Unfreeze.

@type state: bool
    '''
    pass



def setTrackingUnitScale(scale):
    '''
    Set tracking unit scale, default is 1000. vrpn delivers the data always in meter and we use mm.

@param scale: The tracking unit scale.

@type scale: float (32bit)
    '''
    pass



def startTracking():
    '''
    Enables the tracking.
    '''
    pass



def stopTracking():
    '''
    Disables the tracking.
    '''
    pass


