'''
vrVrpnTrackingService
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def getFreezeTracking():
    '''
    Returns Freeze tracking state.
    '''
    pass


def isTracking():
    '''
    Returns true if tracking is currently enabled.
    '''
    pass


def loadTrackingConfig(file):
    '''
    Load tracking configuration from file.
    '''
    pass


def setBodyRelativeToNavigator(name, value):
    '''
    Sets body transformation relative to navigator.
    '''
    pass


def setFreezeTracking(state):
    '''
    Freeze tracking.
    '''
    pass


def setTrackingUnitScale(scale):
    '''
    Set tracking unit scale, default is 1000.
    '''
    pass


def startTracking():
    '''
    Enables the tracking.
    '''
    pass


def stopTracking():
    '''
    Disables the tracking.
    '''
    pass

