
# Autogenerated method stubs for 'vrWebEngineObj.py' module
# VRED Version: 13.0
# 
# VRED-Py - Visual Studio Code Tools for Autodesk VRED
# Copyright: Christopher Gebhardt 2020



def hasWebEngineFocus():
    '''
    Return true if a web engine has the focus.

@return: has focus

@rtype: bool
    '''
    pass



def isWebEngineInteractionEnabled():
    '''
    Return true if interaction with web engines is enabled.

@return: interaction enabled

@rtype: bool
    '''
    pass



def sendToWebEngine(name, event, data):
    '''
    Sends a custom event to a web engine.

@param name: The name of the web engine.

@type name: string

@param event: The name of the user event.

@type event: string

@param data: The string data.

@type data: string
    '''
    pass



def setWebEngineInteractionEnabled(enabled):
    '''
    Enables or disables the interaction with all web engines in the scene.

@param enabled: Enabled/disabled.

@type enabled: bool
    '''
    pass


