'''
vrWebEngineObj
------------------------------------------
API version: v1 | Generation Date: 2020-05-01 | VRED-Py: Visual Studio Code Tools for Autodesk VRED | Autogenerated Method-Stubs

------------------------------------------

'''

from typing import List


def hasWebEngineFocus():
    '''
    Return true if a web engine has the focus.
    '''
    pass


def isWebEngineInteractionEnabled():
    '''
    Return true if interaction with web engines is enabled.
    '''
    pass


def sendToWebEngine(data, event, name):
    '''
    Sends a custom event to a web engine.
    '''
    pass


def setWebEngineInteractionEnabled(enabled):
    '''
    Enables or disables the interaction with all web engines in the scene.
    '''
    pass

